// Generated by AI on 06/15/2026
// Modified by AI on 06/15/2026. Edit #1 - add activeId to ConfigData.

export interface JavaVersion {
  id: string;
  name: string;
  path: string;
}

export interface AppSettings {
  envVarName: string;
}

export interface ConfigData {
  settings: AppSettings;
  versions: JavaVersion[];
  activeId: string | null;
}

export interface SwitchResult {
  success: boolean;
  message: string;
}

export interface ApiError {
  error: string;
  details?: string;
}
