// Generated by AI on 06/15/2026

import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { AddVersionForm } from '../components/AddVersionForm';

describe('AddVersionForm', () => {
  it('renders the Add Java Version button', () => {
    render(<AddVersionForm onAdd={vi.fn()} />);
    expect(screen.getByText(/add java version/i)).toBeInTheDocument();
  });

  it('opens the modal when button is clicked', () => {
    render(<AddVersionForm onAdd={vi.fn()} />);
    fireEvent.click(screen.getByText(/add java version/i));
    expect(screen.getByRole('dialog')).toBeInTheDocument();
    expect(screen.getByLabelText(/version name/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/jdk installation path/i)).toBeInTheDocument();
  });

  it('shows inline error when submitted with empty fields', async () => {
    render(<AddVersionForm onAdd={vi.fn()} />);
    fireEvent.click(screen.getByText(/add java version/i));
    fireEvent.click(screen.getByRole('button', { name: /^save$/i }));
    await waitFor(() => {
      expect(screen.getByText(/version name is required/i)).toBeInTheDocument();
    });
  });

  it('calls onAdd with name and path when form is valid', async () => {
    const onAdd = vi.fn().mockResolvedValue(undefined);
    render(<AddVersionForm onAdd={onAdd} />);
    fireEvent.click(screen.getByText(/add java version/i));
    fireEvent.change(screen.getByLabelText(/version name/i), { target: { value: 'Java 21 LTS' } });
    fireEvent.change(screen.getByLabelText(/jdk installation path/i), { target: { value: 'C:\\jdk21' } });
    fireEvent.click(screen.getByRole('button', { name: /^save$/i }));
    await waitFor(() => {
      expect(onAdd).toHaveBeenCalledWith('Java 21 LTS', 'C:\\jdk21');
    });
  });

  it('shows inline error when onAdd throws', async () => {
    const onAdd = vi.fn().mockRejectedValue(new Error('Directory does not exist'));
    render(<AddVersionForm onAdd={onAdd} />);
    fireEvent.click(screen.getByText(/add java version/i));
    fireEvent.change(screen.getByLabelText(/version name/i), { target: { value: 'Java 21' } });
    fireEvent.change(screen.getByLabelText(/jdk installation path/i), { target: { value: 'C:\\bad' } });
    fireEvent.click(screen.getByRole('button', { name: /^save$/i }));
    await waitFor(() => {
      expect(screen.getByText(/directory does not exist/i)).toBeInTheDocument();
    });
  });
});
