// Generated by AI on 06/15/2026

import { useState, FormEvent } from 'react';
import { Button, Form, Modal } from 'react-bootstrap';
import { PlusCircleIcon } from '@heroicons/react/24/solid';

interface AddVersionFormProps {
  onAdd: (name: string, path: string) => Promise<void>;
}

const INJECTION_PATTERN = /[&|;<>`$()'\n\r]/;
const MAX_PATH_LENGTH = 260;

export function AddVersionForm({ onAdd }: AddVersionFormProps) {
  const [show, setShow] = useState(false);
  const [name, setName] = useState('');
  const [path, setPath] = useState('');
  const [nameError, setNameError] = useState('');
  const [pathError, setPathError] = useState('');
  const [saving, setSaving] = useState(false);

  const validate = (): boolean => {
    let valid = true;
    setNameError('');
    setPathError('');

    if (!name.trim()) {
      setNameError('Version name is required.');
      valid = false;
    }
    if (!path.trim()) {
      setPathError('JDK path is required.');
      valid = false;
    } else if (path.length > MAX_PATH_LENGTH) {
      setPathError(`Path must not exceed ${MAX_PATH_LENGTH} characters.`);
      valid = false;
    } else if (INJECTION_PATTERN.test(path)) {
      setPathError('Path contains invalid characters.');
      valid = false;
    }
    return valid;
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!validate()) return;
    setSaving(true);
    try {
      await onAdd(name.trim(), path.trim());
      setName('');
      setPath('');
      setShow(false);
    } catch (err) {
      setPathError((err as Error).message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <>
      <Button variant="success" onClick={() => setShow(true)} className="d-flex align-items-center gap-2">
        <PlusCircleIcon style={{ width: 20, height: 20 }} aria-hidden="true" />
        Add Java Version
      </Button>

      <Modal show={show} onHide={() => setShow(false)} centered>
        <Modal.Header closeButton>
          <Modal.Title>Add Java Version</Modal.Title>
        </Modal.Header>
        <Form onSubmit={(e) => { void handleSubmit(e); }}>
          <Modal.Body>
            <Form.Group className="mb-3" controlId="versionName">
              <Form.Label>Version Name</Form.Label>
              <Form.Control
                type="text"
                placeholder="e.g. Java 21 LTS"
                value={name}
                onChange={(e) => setName(e.target.value)}
                isInvalid={!!nameError}
                autoFocus
              />
              <Form.Control.Feedback type="invalid">{nameError}</Form.Control.Feedback>
            </Form.Group>
            <Form.Group className="mb-3" controlId="jdkPath">
              <Form.Label>JDK Installation Path</Form.Label>
              <Form.Control
                type="text"
                placeholder="e.g. C:\Program Files\Java\jdk-21"
                value={path}
                onChange={(e) => setPath(e.target.value)}
                isInvalid={!!pathError}
              />
              <Form.Text className="text-muted">
                Enter the full path to the JDK installation directory.
              </Form.Text>
              <Form.Control.Feedback type="invalid">{pathError}</Form.Control.Feedback>
            </Form.Group>
          </Modal.Body>
          <Modal.Footer>
            <Button variant="secondary" onClick={() => setShow(false)}>Cancel</Button>
            <Button type="submit" variant="primary" disabled={saving}>
              {saving ? 'Saving…' : 'Save'}
            </Button>
          </Modal.Footer>
        </Form>
      </Modal>
    </>
  );
}
