// Generated by AI on 06/15/2026

import { useState, useEffect } from 'react';
import { Button, Form, Modal } from 'react-bootstrap';
import { JavaVersion } from '../types';

const INJECTION_PATTERN = /[&|;<>`$()'\n\r]/;

interface EditVersionModalProps {
  version: JavaVersion | null;
  onSave: (id: string, name: string, path: string) => Promise<void>;
  onClose: () => void;
}

export function EditVersionModal({ version, onSave, onClose }: EditVersionModalProps) {
  const [name, setName] = useState('');
  const [path, setPath] = useState('');
  const [nameError, setNameError] = useState('');
  const [pathError, setPathError] = useState('');
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (version) {
      setName(version.name);
      setPath(version.path);
      setNameError('');
      setPathError('');
    }
  }, [version]);

  const validate = (): boolean => {
    let valid = true;
    setNameError('');
    setPathError('');

    if (!name.trim()) {
      setNameError('Version name is required.');
      valid = false;
    } else if (name.trim().length > 100) {
      setNameError('Name must not exceed 100 characters.');
      valid = false;
    }

    if (!path.trim()) {
      setPathError('JDK path is required.');
      valid = false;
    } else if (path.length > 260) {
      setPathError('Path must not exceed 260 characters.');
      valid = false;
    } else if (INJECTION_PATTERN.test(path)) {
      setPathError('Path contains disallowed characters.');
      valid = false;
    }

    return valid;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!version || !validate()) return;

    setSaving(true);
    try {
      await onSave(version.id, name.trim(), path.trim());
      onClose();
    } catch (err) {
      setPathError((err as Error).message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <Modal show={!!version} onHide={onClose} centered>
      <Modal.Header closeButton>
        <Modal.Title>Edit Java Version</Modal.Title>
      </Modal.Header>
      <Form onSubmit={(e) => { void handleSubmit(e); }}>
        <Modal.Body>
          <Form.Group className="mb-3" controlId="edit-version-name">
            <Form.Label>Version Name</Form.Label>
            <Form.Control
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              isInvalid={!!nameError}
              placeholder="e.g. Java 21 LTS"
              autoFocus
            />
            <Form.Control.Feedback type="invalid">{nameError}</Form.Control.Feedback>
          </Form.Group>

          <Form.Group controlId="edit-version-path">
            <Form.Label>JDK Path</Form.Label>
            <Form.Control
              type="text"
              value={path}
              onChange={(e) => setPath(e.target.value)}
              isInvalid={!!pathError}
              placeholder="e.g. C:\Program Files\Java\jdk-21"
            />
            <Form.Control.Feedback type="invalid">{pathError}</Form.Control.Feedback>
          </Form.Group>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={onClose} disabled={saving}>
            Cancel
          </Button>
          <Button variant="primary" type="submit" disabled={saving}>
            {saving ? 'Saving…' : 'Save Changes'}
          </Button>
        </Modal.Footer>
      </Form>
    </Modal>
  );
}
