// Generated by AI on 06/15/2026

import { useState, FormEvent } from 'react';
import { Accordion, Button, Form } from 'react-bootstrap';
import { AppSettings } from '../types';

interface SettingsPanelProps {
  settings: AppSettings;
  onSave: (envVarName: string) => Promise<void>;
}

const ENV_VAR_PATTERN = /^[A-Z_][A-Z0-9_]*$/;

export function SettingsPanel({ settings, onSave }: SettingsPanelProps) {
  const [envVarName, setEnvVarName] = useState(settings.envVarName);
  const [error, setError] = useState('');
  const [saved, setSaved] = useState(false);
  const [saving, setSaving] = useState(false);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError('');
    setSaved(false);

    if (!envVarName.trim()) {
      setError('Environment variable name is required.');
      return;
    }
    if (!ENV_VAR_PATTERN.test(envVarName.trim())) {
      setError('Must contain only uppercase letters, digits, and underscores, and start with a letter or underscore.');
      return;
    }

    setSaving(true);
    try {
      await onSave(envVarName.trim());
      setSaved(true);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <Accordion>
      <Accordion.Item eventKey="settings">
        <Accordion.Header>⚙️ Settings</Accordion.Header>
        <Accordion.Body>
          <Form onSubmit={(e) => { void handleSubmit(e); }}>
            <Form.Group className="mb-3" controlId="envVarName">
              <Form.Label>Environment Variable Name</Form.Label>
              <Form.Control
                type="text"
                value={envVarName}
                onChange={(e) => { setEnvVarName(e.target.value); setSaved(false); }}
                isInvalid={!!error}
                placeholder="JAVA_HOME"
              />
              <Form.Text className="text-muted">
                Uppercase letters, digits, and underscores only (e.g. <code>JAVA_HOME</code>).
              </Form.Text>
              <Form.Control.Feedback type="invalid">{error}</Form.Control.Feedback>
            </Form.Group>
            {saved && <div className="text-success mb-2">Settings saved.</div>}
            <Button type="submit" variant="primary" size="sm" disabled={saving}>
              {saving ? 'Saving…' : 'Save Settings'}
            </Button>
          </Form>
        </Accordion.Body>
      </Accordion.Item>
    </Accordion>
  );
}
