// Generated by AI on 06/15/2026

import { Accordion } from 'react-bootstrap';

export function SetupGuide() {
  return (
    <Accordion className="mt-3">
      <Accordion.Item eventKey="setup">
        <Accordion.Header>📖 How to Add a Java Version</Accordion.Header>
        <Accordion.Body>
          <p>
            <strong>Download Java:</strong>{' '}
            <a
              href="https://www.oracle.com/java/technologies/downloads/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Oracle Java Downloads ↗
            </a>
          </p>
          <ol>
            <li>
              Visit the link above and choose the Java version you want (e.g. JDK 21).
            </li>
            <li>
              Select the <strong>Windows x64 Installer</strong> (.exe) and download it.
            </li>
            <li>
              Run the installer. By default, Java installs to:{' '}
              <code>C:\Program Files\Java\jdk-21</code> (the folder name reflects the version).
            </li>
            <li>
              After installation, open <strong>File Explorer</strong> and navigate to{' '}
              <code>C:\Program Files\Java\</code>. Copy the full path of the new JDK folder.
            </li>
            <li>
              Come back here, click <strong>Add Java Version</strong>, give it a display name,
              paste the path, and click Save.
            </li>
          </ol>
          <p className="text-muted mb-0">
            <strong>Note:</strong> After clicking a version button, open a{' '}
            <strong>new terminal window</strong> for the environment variable change to take effect.
          </p>
        </Accordion.Body>
      </Accordion.Item>
    </Accordion>
  );
}
