// Generated by AI on 06/15/2026

import { render, screen, fireEvent } from '@testing-library/react';
import { VersionButton } from '../components/VersionButton';
import { VersionList } from '../components/VersionList';

const mockVersion = { id: 'id-1', name: 'Java 21 LTS', path: 'C:\\jdk21' };
const mockVersion2 = { id: 'id-2', name: 'Java 17', path: 'C:\\jdk17' };

describe('VersionButton', () => {
  it('renders the version name', () => {
    render(
      <VersionButton
        version={mockVersion}
        isActive={false}
        isSwitching={false}
        onSwitch={vi.fn()}
        onDelete={vi.fn()}
        onEdit={vi.fn()}
      />
    );
    expect(screen.getByText('Java 21 LTS')).toBeInTheDocument();
  });

  it('applies active styles when isActive is true', () => {
    render(
      <VersionButton
        version={mockVersion}
        isActive={true}
        isSwitching={false}
        onSwitch={vi.fn()}
        onDelete={vi.fn()}
        onEdit={vi.fn()}
      />
    );
    const btn = screen.getByRole('button', { name: /switch to java 21 lts/i });
    expect(btn).toHaveClass('btn-primary');
  });

  it('calls onSwitch with the version id when clicked', () => {
    const onSwitch = vi.fn();
    render(
      <VersionButton
        version={mockVersion}
        isActive={false}
        isSwitching={false}
        onSwitch={onSwitch}
        onDelete={vi.fn()}
        onEdit={vi.fn()}
      />
    );
    fireEvent.click(screen.getByRole('button', { name: /switch to java 21 lts/i }));
    expect(onSwitch).toHaveBeenCalledWith('id-1');
  });

  it('is disabled when isSwitching is true', () => {
    render(
      <VersionButton
        version={mockVersion}
        isActive={false}
        isSwitching={true}
        onSwitch={vi.fn()}
        onDelete={vi.fn()}
        onEdit={vi.fn()}
      />
    );
    expect(screen.getByRole('button', { name: /switch to java 21 lts/i })).toBeDisabled();
  });
});

describe('VersionList', () => {
  it('renders a message when no versions provided', () => {
    render(
      <VersionList
        versions={[]}
        activeId={null}
        switchingId={null}
        onSwitch={vi.fn()}
        onDelete={vi.fn()}
        onEdit={vi.fn()}
      />
    );
    expect(screen.getByText(/no java versions configured/i)).toBeInTheDocument();
  });

  it('renders all version buttons', () => {
    render(
      <VersionList
        versions={[mockVersion, mockVersion2]}
        activeId={null}
        switchingId={null}
        onSwitch={vi.fn()}
        onDelete={vi.fn()}
        onEdit={vi.fn()}
      />
    );
    expect(screen.getByText('Java 21 LTS')).toBeInTheDocument();
    expect(screen.getByText('Java 17')).toBeInTheDocument();
  });

  it('marks the active version', () => {
    render(
      <VersionList
        versions={[mockVersion, mockVersion2]}
        activeId="id-1"
        switchingId={null}
        onSwitch={vi.fn()}
        onDelete={vi.fn()}
        onEdit={vi.fn()}
      />
    );
    expect(screen.getByRole('button', { name: /switch to java 21 lts/i })).toHaveClass('btn-primary');
    expect(screen.getByRole('button', { name: /switch to java 17/i })).not.toHaveClass('btn-primary');
  });
});
