// Generated by AI on 06/15/2026

import { JavaVersion } from '../types';
import { VersionButton } from './VersionButton';

interface VersionListProps {
  versions: JavaVersion[];
  activeId: string | null;
  switchingId: string | null;
  onSwitch: (id: string) => void;
  onDelete: (id: string) => void;
}

export function VersionList({ versions, activeId, switchingId, onSwitch, onDelete }: VersionListProps) {
  if (versions.length === 0) {
    return (
      <div className="text-muted text-center py-4">
        No Java versions configured. Add one below.
      </div>
    );
  }

  return (
    <div className="row">
      {versions.map((v) => (
        <div key={v.id} className="col-12 col-md-6 col-lg-4">
          <VersionButton
            version={v}
            isActive={activeId === v.id}
            isSwitching={switchingId === v.id}
            onSwitch={onSwitch}
            onDelete={onDelete}
          />
        </div>
      ))}
    </div>
  );
}
