// Generated by AI on 06/15/2026

import { useState } from 'react';
import { Button, Spinner } from 'react-bootstrap';
import { CheckCircleIcon, TrashIcon, ArrowPathIcon } from '@heroicons/react/24/solid';
import { JavaVersion } from '../types';

interface VersionButtonProps {
  version: JavaVersion;
  isActive: boolean;
  isSwitching: boolean;
  onSwitch: (id: string) => void;
  onDelete: (id: string) => void;
}

export function VersionButton({ version, isActive, isSwitching, onSwitch, onDelete }: VersionButtonProps) {
  const [hovered, setHovered] = useState(false);

  return (
    <div
      className="d-flex align-items-center gap-2 mb-2"
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      <Button
        variant={isActive ? 'primary' : 'outline-primary'}
        className="flex-grow-1 d-flex align-items-center justify-content-between"
        onClick={() => onSwitch(version.id)}
        disabled={isSwitching}
        aria-label={`Switch to ${version.name}`}
      >
        <span>{version.name}</span>
        <span className="d-flex align-items-center gap-1 ms-2">
          {isSwitching && (
            <ArrowPathIcon
              className="icon-spin"
              style={{ width: 16, height: 16 }}
              aria-hidden="true"
            />
          )}
          {isActive && !isSwitching && (
            <CheckCircleIcon style={{ width: 16, height: 16 }} aria-hidden="true" />
          )}
        </span>
      </Button>
      <Button
        variant="outline-danger"
        size="sm"
        onClick={() => onDelete(version.id)}
        aria-label={`Delete ${version.name}`}
        style={{ opacity: hovered ? 1 : 0, transition: 'opacity 0.15s', minWidth: 36 }}
        tabIndex={hovered ? 0 : -1}
      >
        <TrashIcon style={{ width: 16, height: 16 }} aria-hidden="true" />
      </Button>
    </div>
  );
}
