// Generated by AI on 06/15/2026
// Modified by AI on 06/15/2026. Edit #1 - pass onEdit through to VersionButton.

import { JavaVersion } from '../types';
import { VersionButton } from './VersionButton';

interface VersionListProps {
  versions: JavaVersion[];
  activeId: string | null;
  switchingId: string | null;
  onSwitch: (id: string) => void;
  onDelete: (id: string) => void;
  onEdit: (version: JavaVersion) => void;
}

export function VersionList({ versions, activeId, switchingId, onSwitch, onDelete, onEdit }: VersionListProps) {
  if (versions.length === 0) {
    return (
      <div className="text-muted text-center py-4">
        No Java versions configured. Add one below.
      </div>
    );
  }

  return (
    <div>
      {versions.map((v) => (
        <VersionButton
          key={v.id}
          version={v}
          isActive={activeId === v.id}
          isSwitching={switchingId === v.id}
          onSwitch={onSwitch}
          onDelete={onDelete}
          onEdit={onEdit}
        />
      ))}
    </div>
  );
}
