// Generated by AI on 06/15/2026
// Modified by AI on 06/15/2026. Edit #1 - redesign to card layout with visible path, explicit activate/edit/delete actions.

import { Badge, Button, Card, Spinner } from 'react-bootstrap';
import { CheckCircleIcon, PencilSquareIcon, TrashIcon } from '@heroicons/react/24/solid';
import { JavaVersion } from '../types';

interface VersionButtonProps {
  version: JavaVersion;
  isActive: boolean;
  isSwitching: boolean;
  onSwitch: (id: string) => void;
  onDelete: (id: string) => void;
  onEdit: (version: JavaVersion) => void;
}

export function VersionButton({ version, isActive, isSwitching, onSwitch, onDelete, onEdit }: VersionButtonProps) {
  return (
    <Card
      className={`mb-2 shadow-sm ${isActive ? 'border-success' : 'border-light'}`}
      style={{ transition: 'border-color 0.15s' }}
    >
      <Card.Body className="d-flex align-items-center gap-3 py-2 px-3">
        <div className="flex-grow-1 overflow-hidden">
          <div className="d-flex align-items-center gap-2">
            <span className="fw-semibold">{version.name}</span>
            {isActive && (
              <Badge bg="success" pill>
                Active
              </Badge>
            )}
          </div>
          <small className="text-muted d-block text-truncate" title={version.path}>
            {version.path}
          </small>
        </div>

        <div className="d-flex gap-1 align-items-center flex-shrink-0">
          <Button
            variant={isActive ? 'success' : 'primary'}
            size="sm"
            onClick={() => onSwitch(version.id)}
            disabled={isSwitching || isActive}
            aria-label={isActive ? `${version.name} is active` : `Activate ${version.name}`}
            title={isActive ? 'Already active' : 'Activate'}
            style={{ minWidth: 90 }}
          >
            {isSwitching ? (
              <>
                <Spinner animation="border" size="sm" className="me-1" />
                Switching…
              </>
            ) : isActive ? (
              <>
                <CheckCircleIcon style={{ width: 14, height: 14 }} className="me-1" />
                Active
              </>
            ) : (
              'Activate'
            )}
          </Button>

          <Button
            variant="outline-secondary"
            size="sm"
            onClick={() => onEdit(version)}
            aria-label={`Edit ${version.name}`}
            title="Edit"
          >
            <PencilSquareIcon style={{ width: 14, height: 14 }} />
          </Button>

          <Button
            variant="outline-danger"
            size="sm"
            onClick={() => onDelete(version.id)}
            aria-label={`Delete ${version.name}`}
            title="Delete"
          >
            <TrashIcon style={{ width: 14, height: 14 }} />
          </Button>
        </div>
      </Card.Body>
    </Card>
  );
}
