// Generated by AI on 06/15/2026
// Modified by AI on 06/15/2026. Edit #1 - fetch activeId, await switch response, show checkmarks in tray menu.

import { app, BrowserWindow, Tray, Menu } from 'electron';
import path from 'path';
import http from 'http';

// Single-instance lock — prevent duplicate processes
if (!app.requestSingleInstanceLock()) {
  app.quit();
  process.exit(0);
}

const PORT = 3001;
const BACKEND_URL = `http://localhost:${PORT}`;

let mainWindow: BrowserWindow | null = null;
let tray: Tray | null = null;
let isQuitting = false;

function resolveBackendPath(): string {
  if (app.isPackaged) {
    return path.join(process.resourcesPath, 'backend', 'dist', 'server.js');
  }
  // Dev: electron/dist/main.js -> ../../backend/dist/server.js
  return path.join(__dirname, '..', '..', 'backend', 'dist', 'server.js');
}

function resolveIconPath(): string {
  if (app.isPackaged) {
    return path.join(process.resourcesPath, 'assets', 'icon.png');
  }
  // Dev: electron/dist/main.js -> ../assets/icon.png
  return path.join(__dirname, '..', 'assets', 'icon.png');
}

function startBackend(): Promise<void> {
  return new Promise((resolve, reject) => {
    try {
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const expressApp = require(resolveBackendPath()).default as {
        listen: (port: number, cb: () => void) => http.Server;
      };
      const server = expressApp.listen(PORT, () => resolve());
      server.on('error', reject);
    } catch (err) {
      reject(err);
    }
  });
}

function createWindow(): void {
  mainWindow = new BrowserWindow({
    width: 1000,
    height: 700,
    show: false,
    icon: resolveIconPath(),
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  mainWindow.loadURL(BACKEND_URL);

  // Hide to tray on close instead of exiting
  mainWindow.on('close', (e) => {
    if (!isQuitting) {
      e.preventDefault();
      mainWindow?.hide();
    }
  });
}

async function fetchVersions(): Promise<Array<{ id: string; name: string; activeId: string | null }>> {
  return new Promise((resolve) => {
    http
      .get(`${BACKEND_URL}/api/versions`, (res) => {
        let data = '';
        res.on('data', (chunk: string) => { data += chunk; });
        res.on('end', () => {
          try {
            const parsed = JSON.parse(data) as { versions: Array<{ id: string; name: string }>; activeId: string | null };
            const versions = (parsed.versions ?? []).map((v) => ({ ...v, activeId: parsed.activeId ?? null }));
            resolve(versions);
          } catch {
            resolve([]);
          }
        });
      })
      .on('error', () => resolve([]));
  });
}

function switchVersion(id: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const postData = JSON.stringify({ id });
    const req = http.request(
      {
        hostname: 'localhost',
        port: PORT,
        path: '/api/switch',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(postData),
        },
      },
      (res) => {
        let data = '';
        res.on('data', (chunk: string) => { data += chunk; });
        res.on('end', () => {
          try {
            const body = JSON.parse(data) as { success?: boolean; error?: string };
            if (body.success) {
              resolve();
            } else {
              reject(new Error(body.error ?? 'Switch failed'));
            }
          } catch {
            reject(new Error('Invalid response from server'));
          }
        });
      }
    );
    req.on('error', (err: Error) => reject(err));
    req.write(postData);
    req.end();
  });
}

async function buildTrayMenu(): Promise<Menu> {
  const versions = await fetchVersions();
  const activeId = versions.length > 0 ? versions[0].activeId : null;

  const versionItems =
    versions.length > 0
      ? versions.map((v) => ({
          label: `${activeId === v.id ? '✓ ' : '    '}${v.name}`,
          click: async () => {
            try {
              await switchVersion(v.id);
            } catch (err) {
              console.error('Switch error:', (err as Error).message);
            }
          },
        }))
      : [{ label: '(no versions configured)', enabled: false }];

  return Menu.buildFromTemplate([
    {
      label: 'Open Java Context Switcher',
      click: () => {
        mainWindow?.show();
        mainWindow?.focus();
      },
    },
    { type: 'separator' as const },
    ...versionItems,
    { type: 'separator' as const },
    {
      label: 'Quit',
      click: () => {
        isQuitting = true;
        app.quit();
      },
    },
  ]);
}

function createTray(): void {
  tray = new Tray(resolveIconPath());
  tray.setToolTip('Java Context Switcher');

  // Left-click opens the window
  tray.on('click', () => {
    mainWindow?.show();
    mainWindow?.focus();
  });

  // Right-click shows the dynamic context menu with current versions
  tray.on('right-click', async () => {
    const menu = await buildTrayMenu();
    tray?.popUpContextMenu(menu);
  });
}

app.on('second-instance', () => {
  mainWindow?.show();
  mainWindow?.focus();
});

app.whenReady().then(async () => {
  await startBackend();
  createWindow();
  createTray();

  // Modified by AI on 06/15/2026. Edit #1 - only register startup in packaged builds to avoid dev electron.exe in startup.
  if (app.isPackaged) {
    app.setLoginItemSettings({ openAtLogin: true });
  }
});

// Keep the process alive when all windows are closed — lives in tray
app.on('window-all-closed', () => {
  // Intentionally empty: app stays running in system tray
});
