// Generated by AI on 06/15/2026
// Modified by AI on 06/15/2026. Edit #1 - add updateVersion for editing existing entries.
// Modified by AI on 06/16/2026. Edit #2 - sync activeId from API on fetch to stay in sync with tray switches.

import { useState, useEffect, useCallback } from 'react';
import { JavaVersion, AppSettings } from '../types';

const API_BASE = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:3001';

async function handleResponse<T>(res: Response): Promise<T> {
  if (!res.ok) {
    const body = await res.json().catch(() => ({ error: `HTTP ${res.status}` }));
    throw new Error((body as { error: string }).error ?? `HTTP ${res.status}`);
  }
  return res.json() as Promise<T>;
}

export function useVersions() {
  const [versions, setVersions] = useState<JavaVersion[]>([]);
  const [settings, setSettings] = useState<AppSettings>({ envVarName: 'JAVA_HOME' });
  const [activeId, setActiveId] = useState<string | null>(
    localStorage.getItem('activeJavaVersionId')
  );
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchVersions = useCallback(async () => {
    try {
      const data = await handleResponse<{ versions: JavaVersion[]; activeId: string | null }>(
        await fetch(`${API_BASE}/api/versions`)
      );
      setVersions(data.versions);
      // Sync activeId from the server so tray switches are reflected in the UI
      setActiveId(data.activeId);
      if (data.activeId) {
        localStorage.setItem('activeJavaVersionId', data.activeId);
      } else {
        localStorage.removeItem('activeJavaVersionId');
      }
    } catch (err) {
      setError((err as Error).message);
    }
  }, []);

  const fetchSettings = useCallback(async () => {
    try {
      const data = await handleResponse<{ settings: AppSettings }>(
        await fetch(`${API_BASE}/api/settings`)
      );
      setSettings(data.settings);
    } catch (err) {
      setError((err as Error).message);
    }
  }, []);

  useEffect(() => {
    void fetchVersions();
    void fetchSettings();
  }, [fetchVersions, fetchSettings]);

  // Re-fetch when the window becomes visible (e.g. user opens app after switching via tray)
  useEffect(() => {
    const onVisibilityChange = () => {
      if (document.visibilityState === 'visible') {
        void fetchVersions();
      }
    };
    document.addEventListener('visibilitychange', onVisibilityChange);
    return () => document.removeEventListener('visibilitychange', onVisibilityChange);
  }, [fetchVersions]);

  const addVersion = useCallback(async (name: string, path: string): Promise<JavaVersion> => {
    const data = await handleResponse<{ version: JavaVersion }>(
      await fetch(`${API_BASE}/api/versions`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name, path }),
      })
    );
    setVersions((prev) => [...prev, data.version]);
    return data.version;
  }, []);

  const deleteVersion = useCallback(async (id: string): Promise<void> => {
    await handleResponse<{ success: boolean }>(
      await fetch(`${API_BASE}/api/versions/${id}`, { method: 'DELETE' })
    );
    setVersions((prev) => prev.filter((v) => v.id !== id));
    if (activeId === id) {
      setActiveId(null);
      localStorage.removeItem('activeJavaVersionId');
    }
  }, [activeId]);

  // Modified by AI on 06/15/2026. Edit #1 - update an existing version entry via PUT.
  const updateVersion = useCallback(async (id: string, name: string, path: string): Promise<JavaVersion> => {
    const data = await handleResponse<{ version: JavaVersion }>(
      await fetch(`${API_BASE}/api/versions/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name, path }),
      })
    );
    setVersions((prev) => prev.map((v) => (v.id === id ? data.version : v)));
    return data.version;
  }, []);

  const switchVersion = useCallback(async (id: string): Promise<string> => {
    setLoading(true);
    try {
      const data = await handleResponse<{ success: boolean; message: string }>(
        await fetch(`${API_BASE}/api/switch`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ id }),
        })
      );
      setActiveId(id);
      localStorage.setItem('activeJavaVersionId', id);
      return data.message;
    } finally {
      setLoading(false);
    }
  }, []);

  const saveSettings = useCallback(async (envVarName: string): Promise<void> => {
    const data = await handleResponse<{ settings: AppSettings }>(
      await fetch(`${API_BASE}/api/settings`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ envVarName }),
      })
    );
    setSettings(data.settings);
  }, []);

  return { versions, settings, activeId, loading, error, addVersion, updateVersion, deleteVersion, switchVersion, saveSettings, fetchVersions };
}
