// Generated by AI on 06/15/2026

import * as fs from 'fs';
import * as os from 'os';
import * as childProcess from 'child_process';
import { switchVersion } from '../services/batchScript';

jest.mock('fs');
jest.mock('child_process');

const mockFs = fs as jest.Mocked<typeof fs>;
const mockChildProcess = childProcess as jest.Mocked<typeof childProcess>;

describe('batchScript service', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  it('returns success for a valid path and env var', (done) => {
    mockFs.writeFileSync.mockImplementation(() => undefined);
    mockFs.unlinkSync.mockImplementation(() => undefined);
    (mockChildProcess.exec as unknown as jest.Mock).mockImplementation(
      (_cmd: string, _opts: object, callback: (err: null, stdout: string, stderr: string) => void) => {
        callback(null, '', '');
        return {} as childProcess.ChildProcess;
      }
    );

    switchVersion('JAVA_HOME', 'C:\\Program Files\\Java\\jdk-21').then((result) => {
      expect(result.success).toBe(true);
      expect(result.message).toContain('JAVA_HOME');
      expect(mockFs.writeFileSync).toHaveBeenCalledTimes(1);
      expect(mockFs.unlinkSync).toHaveBeenCalledTimes(1);
      done();
    });
  });

  it('rejects paths with injection characters', async () => {
    const injectionPaths = [
      'C:\\jdk & del c:\\',
      'C:\\jdk | cmd',
      'C:\\jdk; echo bad',
      'C:\\jdk > out.txt',
      'C:\\jdk < in.txt',
      'C:\\jdk`echo',
      'C:\\jdk$(evil)',
    ];

    for (const badPath of injectionPaths) {
      const result = await switchVersion('JAVA_HOME', badPath);
      expect(result.success).toBe(false);
      expect(result.message).toContain('invalid');
    }
    expect(mockFs.writeFileSync).not.toHaveBeenCalled();
  });

  it('rejects paths with newlines', async () => {
    const result = await switchVersion('JAVA_HOME', 'C:\\jdk\nmalicious');
    expect(result.success).toBe(false);
  });

  it('returns failure when exec errors', (done) => {
    mockFs.writeFileSync.mockImplementation(() => undefined);
    mockFs.unlinkSync.mockImplementation(() => undefined);
    (mockChildProcess.exec as unknown as jest.Mock).mockImplementation(
      (_cmd: string, _opts: object, callback: (err: Error, stdout: string, stderr: string) => void) => {
        callback(new Error('Access denied'), '', 'Access denied');
        return {} as childProcess.ChildProcess;
      }
    );

    switchVersion('JAVA_HOME', 'C:\\Program Files\\Java\\jdk-21').then((result) => {
      expect(result.success).toBe(false);
      expect(result.message).toContain('failed');
      expect(mockFs.unlinkSync).toHaveBeenCalledTimes(1);
      done();
    });
  });

  it('cleans up temp file even when exec fails', (done) => {
    mockFs.writeFileSync.mockImplementation(() => undefined);
    mockFs.unlinkSync.mockImplementation(() => undefined);
    (mockChildProcess.exec as unknown as jest.Mock).mockImplementation(
      (_cmd: string, _opts: object, callback: (err: Error, stdout: string, stderr: string) => void) => {
        callback(new Error('fail'), '', '');
        return {} as childProcess.ChildProcess;
      }
    );

    switchVersion('JAVA_HOME', 'C:\\jdk21').then(() => {
      expect(mockFs.unlinkSync).toHaveBeenCalledTimes(1);
      done();
    });
  });
});
