// Generated by AI on 06/15/2026
// Modified by AI on 06/15/2026. Edit #1 - use setx /M to write system-level environment variable.
// Modified by AI on 06/15/2026. Edit #2 - removed /M flag; use user-level setx so no admin rights are required.
// Modified by AI on 06/15/2026. Edit #3 - spawn elevated PowerShell process for setx /M so system env var is set without requiring the app itself to run as admin.
// Modified by AI on 06/15/2026. Edit #4 - removed elevation wrapper; setx /M run directly as company policy whitelists it for non-admin.

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { exec } from 'child_process';
import { SwitchResult } from '../types';

const INJECTION_PATTERN = /[&|;<>`$()'\n\r]/;

function containsInjectionChars(value: string): boolean {
  return INJECTION_PATTERN.test(value);
}

function getTempScriptPath(): string {
  return path.join(os.tmpdir(), `java-switch-${Date.now()}.bat`);
}

export async function switchVersion(envVarName: string, jdkPath: string): Promise<SwitchResult> {
  if (containsInjectionChars(jdkPath)) {
    return { success: false, message: 'Path contains invalid characters. Please enter a valid directory path.' };
  }

  if (containsInjectionChars(envVarName)) {
    return { success: false, message: 'Environment variable name contains invalid characters.' };
  }

  const scriptPath = getTempScriptPath();
  const scriptContent = `@echo off\nsetx ${envVarName} "${jdkPath}" /M\n`;

  fs.writeFileSync(scriptPath, scriptContent, 'utf-8');

  return new Promise<SwitchResult>((resolve) => {
    exec(scriptPath, { timeout: 10000 }, (err, _stdout, stderr) => {
      try {
        fs.unlinkSync(scriptPath);
      } catch {
        // Best-effort cleanup
      }

      if (err) {
        const detail = stderr || err.message;
        resolve({ success: false, message: `Switch failed: ${detail}` });
      } else {
        resolve({
          success: true,
          message: `${envVarName} set to "${jdkPath}". Open a new terminal window for the change to take effect.`,
        });
      }
    });
  });
}
