// Generated by AI on 06/15/2026

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { ConfigData, JavaVersion } from '../types';

const CONFIG_DIR_NAME = '.java-context-switcher';
const CONFIG_FILE_NAME = 'java-versions.md';

export function getConfigPath(): string {
  return path.join(os.homedir(), CONFIG_DIR_NAME, CONFIG_FILE_NAME);
}

const DEFAULT_CONFIG: ConfigData = {
  settings: { envVarName: 'JAVA_HOME' },
  versions: [],
};

function serializeConfig(config: ConfigData): string {
  const lines: string[] = [
    '# Java Context Switcher Config',
    '',
    '## Settings',
    `- envVarName: ${config.settings.envVarName}`,
    '',
    '## Versions',
  ];

  for (const v of config.versions) {
    lines.push(`- id: ${v.id}`);
    lines.push(`  name: ${v.name}`);
    lines.push(`  path: ${v.path}`);
  }

  return lines.join('\n') + '\n';
}

function parseConfig(content: string): ConfigData {
  const result: ConfigData = {
    settings: { envVarName: 'JAVA_HOME' },
    versions: [],
  };

  if (!content || !content.includes('## Settings')) {
    return result;
  }

  const settingsMatch = content.match(/- envVarName:\s*(.+)/);
  if (settingsMatch) {
    result.settings.envVarName = settingsMatch[1].trim();
  }

  const versionsSection = content.split('## Versions')[1];
  if (!versionsSection) {
    return result;
  }

  const versionBlocks = versionsSection.trim().split(/\n(?=- id:)/);
  for (const block of versionBlocks) {
    if (!block.trim()) continue;
    const idMatch = block.match(/- id:\s*(.+)/);
    const nameMatch = block.match(/name:\s*(.+)/);
    const pathMatch = block.match(/path:\s*(.+)/);
    if (idMatch && nameMatch && pathMatch) {
      const version: JavaVersion = {
        id: idMatch[1].trim(),
        name: nameMatch[1].trim(),
        path: pathMatch[1].trim(),
      };
      result.versions.push(version);
    }
  }

  return result;
}

export function readConfig(): ConfigData {
  const configPath = getConfigPath();

  if (!fs.existsSync(configPath)) {
    ensureConfigDirectory();
    writeConfig(DEFAULT_CONFIG);
    return { ...DEFAULT_CONFIG, versions: [] };
  }

  try {
    const content = fs.readFileSync(configPath, 'utf-8');
    return parseConfig(content);
  } catch {
    return { ...DEFAULT_CONFIG, versions: [] };
  }
}

function ensureConfigDirectory(): void {
  const configDir = path.dirname(getConfigPath());
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }
}

export function writeConfig(config: ConfigData): void {
  const configPath = getConfigPath();
  ensureConfigDirectory();
  const content = serializeConfig(config);
  fs.writeFileSync(configPath, content, 'utf-8');
}
