// Generated by AI on 06/15/2026
// Modified by AI on 06/15/2026. Edit #1 - added activeId tracking.
// Modified by AI on 06/15/2026. Edit #2 - added syncActiveIdFromEnv for startup detection.

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { ConfigData, JavaVersion } from '../types';

const CONFIG_DIR_NAME = '.java-context-switcher';
const CONFIG_FILE_NAME = 'java-versions.md';

export function getConfigPath(): string {
  return path.join(os.homedir(), CONFIG_DIR_NAME, CONFIG_FILE_NAME);
}

// Modified by AI on 06/15/2026. Edit #1 - added activeId tracking.
const DEFAULT_CONFIG: ConfigData = {
  settings: { envVarName: 'JAVA_HOME' },
  versions: [],
  activeId: null,
};

function serializeConfig(config: ConfigData): string {
  const lines: string[] = [
    '# Java Context Switcher Config',
    '',
    '## Settings',
    `- envVarName: ${config.settings.envVarName}`,
    `- activeId: ${config.activeId ?? ''}`,
    '',
    '## Versions',
  ];

  for (const v of config.versions) {
    lines.push(`- id: ${v.id}`);
    lines.push(`  name: ${v.name}`);
    lines.push(`  path: ${v.path}`);
  }

  return lines.join('\n') + '\n';
}

function parseConfig(content: string): ConfigData {
  const result: ConfigData = {
    settings: { envVarName: 'JAVA_HOME' },
    versions: [],
    activeId: null,
  };

  if (!content || !content.includes('## Settings')) {
    return result;
  }

  const settingsMatch = content.match(/- envVarName:\s*(.+)/);
  if (settingsMatch) {
    result.settings.envVarName = settingsMatch[1].trim();
  }

  const activeIdMatch = content.match(/- activeId:\s*(.*)/);
  if (activeIdMatch && activeIdMatch[1].trim().length > 0) {
    result.activeId = activeIdMatch[1].trim();
  }

  const versionsSection = content.split('## Versions')[1];
  if (!versionsSection) {
    return result;
  }

  const versionBlocks = versionsSection.trim().split(/\n(?=- id:)/);
  for (const block of versionBlocks) {
    if (!block.trim()) continue;
    const idMatch = block.match(/- id:\s*(.+)/);
    const nameMatch = block.match(/name:\s*(.+)/);
    const pathMatch = block.match(/path:\s*(.+)/);
    if (idMatch && nameMatch && pathMatch) {
      const version: JavaVersion = {
        id: idMatch[1].trim(),
        name: nameMatch[1].trim(),
        path: pathMatch[1].trim(),
      };
      result.versions.push(version);
    }
  }

  return result;
}

export function readConfig(): ConfigData {
  const configPath = getConfigPath();

  if (!fs.existsSync(configPath)) {
    ensureConfigDirectory();
    writeConfig(DEFAULT_CONFIG);
    return { ...DEFAULT_CONFIG, versions: [] };
  }

  try {
    const content = fs.readFileSync(configPath, 'utf-8');
    return parseConfig(content);
  } catch {
    return { ...DEFAULT_CONFIG, versions: [] };
  }
}

function ensureConfigDirectory(): void {
  const configDir = path.dirname(getConfigPath());
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }
}

/**
 * Called once on startup. Reads the current system value of the configured
 * env var (e.g. JAVA_HOME) and matches it against stored versions by path.
 * If a match is found, persists that version as activeId.
 * If no match, clears activeId so the UI shows nothing as active.
 */
export function syncActiveIdFromEnv(): void {
  try {
    const config = readConfig();
    const currentPath = process.env[config.settings.envVarName];
    if (!currentPath) {
      if (config.activeId !== null) {
        config.activeId = null;
        writeConfig(config);
      }
      return;
    }
    const normalise = (p: string) => p.trim().toLowerCase().replace(/[\\/]+$/, '');
    const match = config.versions.find(
      (v) => normalise(v.path) === normalise(currentPath)
    );
    const resolvedId = match ? match.id : null;
    if (config.activeId !== resolvedId) {
      config.activeId = resolvedId;
      writeConfig(config);
    }
  } catch {
    // Non-fatal — app continues without a detected active version
  }
}

export function writeConfig(config: ConfigData): void {
  const configPath = getConfigPath();
  ensureConfigDirectory();
  const content = serializeConfig(config);
  fs.writeFileSync(configPath, content, 'utf-8');
}
