// Generated by AI on 06/15/2026

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { readConfig, writeConfig, getConfigPath } from '../services/configFile';
import { ConfigData } from '../types';

jest.mock('fs');
const mockFs = fs as jest.Mocked<typeof fs>;

describe('configFile service', () => {
  const testPath = path.join(os.homedir(), '.java-context-switcher', 'java-versions.md');

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('getConfigPath', () => {
    it('returns a path ending in java-versions.md', () => {
      const p = getConfigPath();
      expect(p.endsWith('java-versions.md')).toBe(true);
    });
  });

  describe('readConfig', () => {
    it('parses a valid config file', () => {
      const content = [
        '# Java Context Switcher Config',
        '',
        '## Settings',
        '- envVarName: JAVA_HOME',
        '',
        '## Versions',
        '- id: abc-123',
        '  name: Java 21 LTS',
        '  path: C:\\Program Files\\Java\\jdk-21',
      ].join('\n');

      mockFs.existsSync.mockReturnValue(true);
      mockFs.readFileSync.mockReturnValue(content as unknown as ReturnType<typeof fs.readFileSync>);

      const config = readConfig();
      expect(config.settings.envVarName).toBe('JAVA_HOME');
      expect(config.versions).toHaveLength(1);
      expect(config.versions[0]).toEqual({
        id: 'abc-123',
        name: 'Java 21 LTS',
        path: 'C:\\Program Files\\Java\\jdk-21',
      });
    });

    it('returns defaults when file does not exist', () => {
      mockFs.existsSync.mockReturnValue(false);
      mockFs.mkdirSync.mockImplementation(() => undefined);
      mockFs.writeFileSync.mockImplementation(() => undefined);

      const config = readConfig();
      expect(config.settings.envVarName).toBe('JAVA_HOME');
      expect(config.versions).toHaveLength(0);
    });

    it('returns defaults for empty file', () => {
      mockFs.existsSync.mockReturnValue(true);
      mockFs.readFileSync.mockReturnValue('' as unknown as ReturnType<typeof fs.readFileSync>);

      const config = readConfig();
      expect(config.settings.envVarName).toBe('JAVA_HOME');
      expect(config.versions).toHaveLength(0);
    });

    it('returns defaults for malformed file', () => {
      mockFs.existsSync.mockReturnValue(true);
      mockFs.readFileSync.mockReturnValue('not valid markdown config' as unknown as ReturnType<typeof fs.readFileSync>);

      const config = readConfig();
      expect(config.settings.envVarName).toBe('JAVA_HOME');
      expect(config.versions).toHaveLength(0);
    });

    it('parses multiple versions', () => {
      const content = [
        '# Java Context Switcher Config',
        '',
        '## Settings',
        '- envVarName: JDK_HOME',
        '',
        '## Versions',
        '- id: id-1',
        '  name: Java 8',
        '  path: C:\\jdk8',
        '- id: id-2',
        '  name: Java 17',
        '  path: C:\\jdk17',
      ].join('\n');

      mockFs.existsSync.mockReturnValue(true);
      mockFs.readFileSync.mockReturnValue(content as unknown as ReturnType<typeof fs.readFileSync>);

      const config = readConfig();
      expect(config.settings.envVarName).toBe('JDK_HOME');
      expect(config.versions).toHaveLength(2);
      expect(config.versions[1].name).toBe('Java 17');
    });
  });

  describe('writeConfig', () => {
    it('writes a valid config to file', () => {
      mockFs.existsSync.mockReturnValue(true);
      mockFs.writeFileSync.mockImplementation(() => undefined);

      const config: ConfigData = {
        settings: { envVarName: 'JAVA_HOME' },
        versions: [{ id: 'id-1', name: 'Java 21', path: 'C:\\jdk21' }],
      };

      writeConfig(config);

      expect(mockFs.writeFileSync).toHaveBeenCalledTimes(1);
      const written = (mockFs.writeFileSync.mock.calls[0][1] as string);
      expect(written).toContain('envVarName: JAVA_HOME');
      expect(written).toContain('name: Java 21');
      expect(written).toContain('path: C:\\jdk21');
    });

    it('creates directory if it does not exist', () => {
      mockFs.existsSync.mockReturnValue(false);
      mockFs.mkdirSync.mockImplementation(() => undefined);
      mockFs.writeFileSync.mockImplementation(() => undefined);

      const config: ConfigData = {
        settings: { envVarName: 'JAVA_HOME' },
        versions: [],
      };

      writeConfig(config);
      expect(mockFs.mkdirSync).toHaveBeenCalledWith(
        path.dirname(testPath),
        { recursive: true }
      );
    });
  });
});
