// Generated by AI on 06/16/2026

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

const LOG_DIR = path.join(os.homedir(), '.java-context-switcher');
const LOG_FILE = path.join(LOG_DIR, 'app.log');

function ensureLogDir(): void {
  if (!fs.existsSync(LOG_DIR)) {
    fs.mkdirSync(LOG_DIR, { recursive: true });
  }
}

export function logError(prefix: string, message: string, err?: unknown): void {
  const timestamp = new Date().toISOString();
  const stack = err instanceof Error ? err.stack ?? err.message : String(err ?? '');
  const line = `[${timestamp}] ERROR ${prefix}: ${message}${stack ? '\n' + stack : ''}\n`;

  try {
    ensureLogDir();
    fs.appendFileSync(LOG_FILE, line, 'utf-8');
  } catch {
    // fallback — at minimum write to stderr
  }
  console.error(line.trimEnd());
}

export function logInfo(prefix: string, message: string): void {
  const timestamp = new Date().toISOString();
  const line = `[${timestamp}] INFO  ${prefix}: ${message}\n`;

  try {
    ensureLogDir();
    fs.appendFileSync(LOG_FILE, line, 'utf-8');
  } catch {
    // fallback
  }
  console.log(line.trimEnd());
}
