// Generated by AI on 06/15/2026

export interface JavaVersion {
  id: string;
  name: string;
  path: string;
}

export interface AppSettings {
  envVarName: string;
}

export interface SwitchResult {
  success: boolean;
  message: string;
}

export interface ApiError {
  error: string;
  details?: string;
}
