// Generated by AI on 06/15/2026
// Modified by AI on 06/15/2026. Edit #1 - serve built frontend static files for Electron.
// Modified by AI on 06/15/2026. Edit #2 - sync activeId from system env var on startup.

import express from 'express';
import cors from 'cors';
import path from 'path';
import versionsRouter from './routes/versions';
import switchRouter from './routes/switch';
import settingsRouter from './routes/settings';
import { syncActiveIdFromEnv } from './services/configFile';
import { logError, logInfo } from './services/logger';

const app = express();
const PORT = process.env.PORT ? parseInt(process.env.PORT, 10) : 3001;

// Detect current active Java version from system environment on startup
syncActiveIdFromEnv();

app.use(cors());
app.use(express.json());

app.get('/health', (_req, res) => {
  res.json({ status: 'ok' });
});

app.use('/api', versionsRouter);
app.use('/api', switchRouter);
app.use('/api', settingsRouter);

// Serve the built React frontend (output to dist/public by Vite)
const publicDir = path.join(__dirname, 'public');
app.use(express.static(publicDir));
app.get('*', (_req, res) => {
  res.sendFile(path.join(publicDir, 'index.html'));
});

// Modified by AI on 06/16/2026. Edit #3 - use file logger for global error handler and startup.
// Global error handler
app.use((err: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  logError('server', err.message, err);
  res.status(500).json({ error: 'Internal server error' });
});

if (require.main === module) {
  app.listen(PORT, () => {
    logInfo('server', `Java Context Switcher running on http://localhost:${PORT}`);
  });
}

export default app;
