// Generated by AI on 06/15/2026

import express from 'express';
import cors from 'cors';
import versionsRouter from './routes/versions';
import switchRouter from './routes/switch';
import settingsRouter from './routes/settings';

const app = express();
const PORT = process.env.PORT ? parseInt(process.env.PORT, 10) : 3001;

app.use(cors());
app.use(express.json());

app.get('/health', (_req, res) => {
  res.json({ status: 'ok' });
});

app.use('/api', versionsRouter);
app.use('/api', switchRouter);
app.use('/api', settingsRouter);

// Global error handler
app.use((err: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  console.error(`[${new Date().toISOString()}] Unhandled error:`, err.message);
  res.status(500).json({ error: 'Internal server error' });
});

if (require.main === module) {
  app.listen(PORT, () => {
    console.log(`Java Context Switcher running on http://localhost:${PORT}`);
  });
}

export default app;
