// Generated by AI on 06/15/2026

import request from 'supertest';
import app from '../server';

jest.mock('../services/configFile');
jest.mock('../services/batchScript');

import { readConfig, writeConfig } from '../services/configFile';
import { switchVersion } from '../services/batchScript';

const mockReadConfig = readConfig as jest.MockedFunction<typeof readConfig>;
const mockWriteConfig = writeConfig as jest.MockedFunction<typeof writeConfig>;
const mockSwitchVersion = switchVersion as jest.MockedFunction<typeof switchVersion>;

const baseConfig = () => ({
  settings: { envVarName: 'JAVA_HOME' },
  versions: [
    { id: 'id-1', name: 'Java 21 LTS', path: 'C:\\jdk21' },
    { id: 'id-2', name: 'Java 17', path: 'C:\\jdk17' },
  ],
});

beforeEach(() => {
  jest.clearAllMocks();
  mockReadConfig.mockReturnValue(baseConfig());
  mockWriteConfig.mockImplementation(() => undefined);
});

describe('GET /api/versions', () => {
  it('returns all versions', async () => {
    const res = await request(app).get('/api/versions');
    expect(res.status).toBe(200);
    expect(res.body.versions).toHaveLength(2);
    expect(res.body.versions[0].id).toBe('id-1');
  });
});

describe('POST /api/versions', () => {
  it('adds a new version and returns it', async () => {
    const mockExistsSync = jest.spyOn(require('fs'), 'existsSync').mockReturnValue(true);
    const res = await request(app)
      .post('/api/versions')
      .send({ name: 'Java 11', path: 'C:\\jdk11' });
    expect(res.status).toBe(201);
    expect(res.body.version.name).toBe('Java 11');
    expect(res.body.version.id).toBeDefined();
    expect(mockWriteConfig).toHaveBeenCalledTimes(1);
    mockExistsSync.mockRestore();
  });

  it('returns 400 when name is missing', async () => {
    const res = await request(app)
      .post('/api/versions')
      .send({ path: 'C:\\jdk11' });
    expect(res.status).toBe(400);
    expect(res.body.error).toBeDefined();
  });

  it('returns 400 when path is missing', async () => {
    const res = await request(app)
      .post('/api/versions')
      .send({ name: 'Java 11' });
    expect(res.status).toBe(400);
    expect(res.body.error).toBeDefined();
  });

  it('returns 400 when path does not exist on disk', async () => {
    const mockExistsSync = jest.spyOn(require('fs'), 'existsSync').mockReturnValue(false);
    const res = await request(app)
      .post('/api/versions')
      .send({ name: 'Java 11', path: 'C:\\nonexistent' });
    expect(res.status).toBe(400);
    expect(res.body.error).toContain('does not exist');
    mockExistsSync.mockRestore();
  });

  it('returns 400 when path contains injection chars', async () => {
    const res = await request(app)
      .post('/api/versions')
      .send({ name: 'Java 11', path: 'C:\\jdk & del c:\\' });
    expect(res.status).toBe(400);
  });
});

describe('DELETE /api/versions/:id', () => {
  it('deletes an existing version', async () => {
    const res = await request(app).delete('/api/versions/id-1');
    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(mockWriteConfig).toHaveBeenCalledTimes(1);
  });

  it('returns 404 for unknown id', async () => {
    const res = await request(app).delete('/api/versions/unknown-id');
    expect(res.status).toBe(404);
  });
});

describe('POST /api/switch', () => {
  it('switches version successfully', async () => {
    mockSwitchVersion.mockResolvedValue({ success: true, message: 'JAVA_HOME set.' });
    const res = await request(app).post('/api/switch').send({ id: 'id-1' });
    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(mockSwitchVersion).toHaveBeenCalledWith('JAVA_HOME', 'C:\\jdk21');
  });

  it('returns 400 when id is missing', async () => {
    const res = await request(app).post('/api/switch').send({});
    expect(res.status).toBe(400);
  });

  it('returns 404 when version id not found', async () => {
    const res = await request(app).post('/api/switch').send({ id: 'unknown' });
    expect(res.status).toBe(404);
  });

  it('returns 500 when switch fails', async () => {
    mockSwitchVersion.mockResolvedValue({ success: false, message: 'Access denied.' });
    const res = await request(app).post('/api/switch').send({ id: 'id-1' });
    expect(res.status).toBe(500);
    expect(res.body.error).toBeDefined();
  });
});

describe('GET /api/settings', () => {
  it('returns current settings', async () => {
    const res = await request(app).get('/api/settings');
    expect(res.status).toBe(200);
    expect(res.body.settings.envVarName).toBe('JAVA_HOME');
  });
});

describe('PUT /api/settings', () => {
  it('updates envVarName', async () => {
    const res = await request(app).put('/api/settings').send({ envVarName: 'JDK_HOME' });
    expect(res.status).toBe(200);
    expect(res.body.settings.envVarName).toBe('JDK_HOME');
    expect(mockWriteConfig).toHaveBeenCalledTimes(1);
  });

  it('returns 400 for invalid envVarName', async () => {
    const res = await request(app).put('/api/settings').send({ envVarName: 'invalid name' });
    expect(res.status).toBe(400);
  });

  it('returns 400 when envVarName is missing', async () => {
    const res = await request(app).put('/api/settings').send({});
    expect(res.status).toBe(400);
  });
});
