// Generated by AI on 06/15/2026

import { Router, Request, Response } from 'express';
import { readConfig, writeConfig } from '../services/configFile';
import { logError } from '../services/logger';

const router = Router();

const ENV_VAR_NAME_PATTERN = /^[A-Z_][A-Z0-9_]*$/;
const MAX_ENV_VAR_LENGTH = 64;

// Modified by AI on 06/16/2026. Edit #1 - log errors to console in all catch blocks.
router.get('/settings', (_req: Request, res: Response) => {
  try {
    const config = readConfig();
    res.json({ settings: config.settings });
  } catch (err) {
    logError('settings GET', 'Failed to read settings', err);
    res.status(500).json({ error: 'Failed to read settings' });
  }
});

router.put('/settings', (req: Request, res: Response) => {
  const { envVarName } = req.body as { envVarName?: string };

  if (!envVarName || typeof envVarName !== 'string' || envVarName.trim().length === 0) {
    res.status(400).json({ error: 'envVarName is required' });
    return;
  }
  if (envVarName.trim().length > MAX_ENV_VAR_LENGTH) {
    res.status(400).json({ error: `envVarName must not exceed ${MAX_ENV_VAR_LENGTH} characters` });
    return;
  }
  if (!ENV_VAR_NAME_PATTERN.test(envVarName.trim())) {
    res.status(400).json({
      error: 'envVarName must contain only uppercase letters, digits, and underscores, and must start with a letter or underscore',
    });
    return;
  }

  try {
    const config = readConfig();
    config.settings.envVarName = envVarName.trim();
    writeConfig(config);
    res.json({ settings: config.settings });
  } catch (err) {
    logError('settings PUT', 'Failed to save settings', err);
    res.status(500).json({ error: 'Failed to save settings' });
  }
});

export default router;
