// Generated by AI on 06/15/2026
// Modified by AI on 06/15/2026. Edit #1 - persist activeId in config on successful switch.

import { Router, Request, Response } from 'express';
import { readConfig, writeConfig } from '../services/configFile';
import { switchVersion } from '../services/batchScript';

const router = Router();

router.post('/switch', async (req: Request, res: Response) => {
  const { id } = req.body as { id?: string };

  if (!id || typeof id !== 'string' || id.trim().length === 0) {
    res.status(400).json({ error: 'Version id is required' });
    return;
  }

  try {
    const config = readConfig();
    const version = config.versions.find((v) => v.id === id.trim());
    if (!version) {
      console.info(`[switch] Version not found. Requested id: '${id}'. Known ids: [${config.versions.map((v) => v.id).join(', ')}]`);
      res.status(404).json({ error: `Version with id '${id}' not found` });
      return;
    }

    const result = await switchVersion(config.settings.envVarName, version.path);
    if (result.success) {
      config.activeId = version.id;
      writeConfig(config);
      res.json({ success: true, message: result.message });
    } else {
      res.status(500).json({ error: result.message });
    }
  } catch (err) {
    // Modified by AI on 06/16/2026. Edit #1 - log errors to console.
    console.error('[switch] Failed to switch version:', (err as Error).message, err);
    res.status(500).json({ error: 'Failed to switch version' });
  }
});

export default router;
