// Generated by AI on 06/15/2026
// Modified by AI on 06/15/2026. Edit #1 - add PUT /versions/:id for editing existing entries.

import { Router, Request, Response } from 'express';
import * as fs from 'fs';
import { v4 as uuidv4 } from 'uuid';
import { readConfig, writeConfig } from '../services/configFile';

const router = Router();

const INJECTION_PATTERN = /[&|;<>`$()'\n\r]/;
const MAX_PATH_LENGTH = 260;
const MAX_NAME_LENGTH = 100;

// Modified by AI on 06/16/2026. Edit #2 - log errors to console in all catch blocks.
router.get('/versions', (_req: Request, res: Response) => {
  try {
    const config = readConfig();
    res.json({ versions: config.versions, activeId: config.activeId ?? null });
  } catch (err) {
    console.error('[versions GET] Failed to read versions:', (err as Error).message, err);
    res.status(500).json({ error: 'Failed to read versions' });
  }
});

router.post('/versions', (req: Request, res: Response) => {
  const { name, path: jdkPath } = req.body as { name?: string; path?: string };

  if (!name || typeof name !== 'string' || name.trim().length === 0) {
    res.status(400).json({ error: 'Version name is required' });
    return;
  }
  if (name.trim().length > MAX_NAME_LENGTH) {
    res.status(400).json({ error: `Version name must not exceed ${MAX_NAME_LENGTH} characters` });
    return;
  }
  if (!jdkPath || typeof jdkPath !== 'string' || jdkPath.trim().length === 0) {
    res.status(400).json({ error: 'JDK path is required' });
    return;
  }
  if (jdkPath.length > MAX_PATH_LENGTH) {
    res.status(400).json({ error: `Path must not exceed ${MAX_PATH_LENGTH} characters` });
    return;
  }
  if (INJECTION_PATTERN.test(jdkPath)) {
    res.status(400).json({ error: 'Path contains disallowed characters' });
    return;
  }
  if (!fs.existsSync(jdkPath.trim())) {
    res.status(400).json({ error: `Directory does not exist: ${jdkPath.trim()}` });
    return;
  }

  try {
    const config = readConfig();
    const newVersion = { id: uuidv4(), name: name.trim(), path: jdkPath.trim() };
    config.versions.push(newVersion);
    writeConfig(config);
    res.status(201).json({ version: newVersion });
  } catch (err) {
    console.error('[versions POST] Failed to save version:', (err as Error).message, err);
    res.status(500).json({ error: 'Failed to save version' });
  }
});

// Modified by AI on 06/15/2026. Edit #1 - PUT handler for editing an existing version entry.
router.put('/versions/:id', (req: Request, res: Response) => {
  const { id } = req.params;
  const { name, path: jdkPath } = req.body as { name?: string; path?: string };

  if (!name || typeof name !== 'string' || name.trim().length === 0) {
    res.status(400).json({ error: 'Version name is required' });
    return;
  }
  if (name.trim().length > MAX_NAME_LENGTH) {
    res.status(400).json({ error: `Version name must not exceed ${MAX_NAME_LENGTH} characters` });
    return;
  }
  if (!jdkPath || typeof jdkPath !== 'string' || jdkPath.trim().length === 0) {
    res.status(400).json({ error: 'JDK path is required' });
    return;
  }
  if (jdkPath.length > MAX_PATH_LENGTH) {
    res.status(400).json({ error: `Path must not exceed ${MAX_PATH_LENGTH} characters` });
    return;
  }
  if (INJECTION_PATTERN.test(jdkPath)) {
    res.status(400).json({ error: 'Path contains disallowed characters' });
    return;
  }
  if (!fs.existsSync(jdkPath.trim())) {
    res.status(400).json({ error: `Directory does not exist: ${jdkPath.trim()}` });
    return;
  }

  try {
    const config = readConfig();
    const index = config.versions.findIndex((v) => v.id === id);
    if (index === -1) {
      res.status(404).json({ error: `Version with id '${id}' not found` });
      return;
    }
    config.versions[index] = { id, name: name.trim(), path: jdkPath.trim() };
    writeConfig(config);
    res.json({ version: config.versions[index] });
  } catch (err) {
    console.error('[versions PUT] Failed to update version:', (err as Error).message, err);
    res.status(500).json({ error: 'Failed to update version' });
  }
});

router.delete('/versions/:id', (req: Request, res: Response) => {  const { id } = req.params;
  try {
    const config = readConfig();
    const index = config.versions.findIndex((v) => v.id === id);
    if (index === -1) {
      res.status(404).json({ error: `Version with id '${id}' not found` });
      return;
    }
    config.versions.splice(index, 1);
    writeConfig(config);
    res.json({ success: true });
  } catch (err) {
    console.error('[versions DELETE] Failed to delete version:', (err as Error).message, err);
    res.status(500).json({ error: 'Failed to delete version' });
  }
});

export default router;
