#!/usr/bin/env pwsh
# Generated by AI on 10/31/2024
<#
.SYNOPSIS
    Deep Business Logic Analyzer

.DESCRIPTION
    Exhaustively traces business logic flows by identifying entry points and following
    execution paths through the codebase. Generates hierarchical data flow diagrams
    showing how requests flow through the application.

.PARAMETER RepositoryPath
    Path to repository to analyze

.PARAMETER MaxDepth
    Maximum depth to trace calls (default: 10)

.PARAMETER IncludeTests
    Include test files in analysis

.EXAMPLE
    .\Analyze-BusinessLogic.ps1 -RepositoryPath "C:\MyRepo"
#>

param(
    [string]$RepositoryPath = ".",
    [int]$MaxDepth = 10,
    [switch]$IncludeTests = $false
)

$RepositoryPath = Resolve-Path $RepositoryPath

Write-Host "🔍 Deep Business Logic Analysis..." -ForegroundColor Cyan

function Get-CSharpFiles {
    return Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*.cs" -ErrorAction SilentlyContinue | 
        Where-Object { 
            $_.FullName -notlike "*\bin\*" -and 
            $_.FullName -notlike "*\obj\*" -and
            ($IncludeTests -or ($_.Name -notlike "*test*" -and $_.Name -notlike "*Test*"))
        }
}

function Get-TypeScriptFiles {
    return Get-ChildItem -Path $RepositoryPath -Recurse -Include "*.ts", "*.tsx" -ErrorAction SilentlyContinue | 
        Where-Object { 
            $_.FullName -notlike "*\node_modules\*" -and
            $_.FullName -notlike "*\dist\*" -and
            ($IncludeTests -or ($_.Name -notlike "*.test.ts" -and $_.Name -notlike "*.spec.ts"))
        }
}

function Find-EntryPoints {
    Write-Host "  🎯 Finding entry points..." -ForegroundColor Gray
    
    $entryPoints = @{
        Controllers = @()
        AzureFunctions = @()
        MessageHandlers = @()
        BackgroundJobs = @()
        GraphQLResolvers = @()
        SignalRHubs = @()
        gRPCServices = @()
        Endpoints = @()
    }
    
    $csFiles = Get-CSharpFiles
    
    foreach ($file in $csFiles) {
        try {
            $content = Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue
            if (-not $content) { continue }
            
            $relativePath = $file.FullName.Replace($RepositoryPath, "").TrimStart('\', '/')
            
            # MVC/API Controllers - detect by inheritance or [ApiController] attribute
            $isController = $false
            $className = $null
            
            # Check for direct inheritance from Controller, ControllerBase, or ApiController
            if ($content -match 'class\s+(\w+)\s*:\s*(?:Controller|ControllerBase|ApiController)') {
                $isController = $true
                $className = $Matches[1]
            }
            # Check for [ApiController] attribute (covers custom base classes)
            elseif ($content -match '\[ApiController\]\s+(?:\[.*?\]\s+)*(?:public|internal)\s+(?:partial\s+)?class\s+(\w+)') {
                $isController = $true
                $className = $Matches[1]
            }
            # Check for inheritance from any class ending with "Controller" (custom base classes)
            elseif ($content -match 'class\s+(\w+)\s*:\s*\w*Controller') {
                $isController = $true
                $className = $Matches[1]
            }
            
            if ($isController -and $className) {
                $methods = [regex]::Matches($content, '\[Http(Get|Post|Put|Delete|Patch)\(?.*?\)?\]\s*(?:\[.*?\]\s*)*(?:public|internal)\s+(?:async\s+)?(?:Task<)?(\w+)(?:>)?\s+(\w+)\s*\(([^)]*)\)')
                
                $endpoints = @()
                foreach ($method in $methods) {
                    $httpVerb = $method.Groups[1].Value
                    $returnType = $method.Groups[2].Value
                    $methodName = $method.Groups[3].Value
                    $parameters = $method.Groups[4].Value
                    
                    # Extract route
                    $routeMatch = [regex]::Match($content, "\[Route\(`"([^`"]+)`"\)\]\s*(?:\[.*?\]\s*)*public\s+(?:async\s+)?(?:Task<)?$returnType(?:>)?\s+$methodName")
                    $route = if ($routeMatch.Success) { $routeMatch.Groups[1].Value } else { "/{controller}/$methodName" }
                    
                    $endpoints += @{
                        Method = $methodName
                        HttpVerb = $httpVerb
                        Route = $route
                        ReturnType = $returnType
                        Parameters = $parameters.Trim()
                    }
                }
                
                if ($endpoints.Count -gt 0) {
                    $entryPoints.Controllers += @{
                        Name = $className
                        File = $relativePath
                        Endpoints = $endpoints
                    }
                }
            }
            
            # Azure Functions - supports both [FunctionName("name")] (v1) and [Function(nameof(Class))] (v4+)
            if ($content -match '\[Function(?:Name)?\(') {
                # Extract class name for Azure Functions
                $azureFunctionClassName = $null
                if ($content -match 'class\s+(\w+)') {
                    $azureFunctionClassName = $Matches[1]
                }
                
                # Pattern for [FunctionName("name")] - Azure Functions v1-v3
                $functionMatches = [regex]::Matches($content, '\[FunctionName\("([^"]+)"\)\]\s*(?:\[.*?\]\s*)*(?:public|internal|private|protected)?\s*(?:static\s+)?(?:async\s+)?(?:Task<)?(\w+)(?:>)?\s+(\w+)\s*\(([^)]*)\)')
                
                foreach ($funcMatch in $functionMatches) {
                    $functionName = $funcMatch.Groups[1].Value
                    $returnType = $funcMatch.Groups[2].Value
                    $methodName = $funcMatch.Groups[3].Value
                    $parameters = $funcMatch.Groups[4].Value
                    
                    # Determine trigger type
                    $triggerType = "Unknown"
                    if ($parameters -match 'HttpTrigger') { $triggerType = "HTTP" }
                    elseif ($parameters -match 'TimerTrigger') { $triggerType = "Timer" }
                    elseif ($parameters -match 'ServiceBusTrigger') { $triggerType = "ServiceBus" }
                    elseif ($parameters -match 'QueueTrigger') { $triggerType = "Queue" }
                    elseif ($parameters -match 'BlobTrigger') { $triggerType = "Blob" }
                    elseif ($parameters -match 'EventHubTrigger') { $triggerType = "EventHub" }
                    elseif ($parameters -match 'EventGridTrigger') { $triggerType = "EventGrid" }
                    
                    $entryPoints.AzureFunctions += @{
                        Name = $functionName
                        Method = $methodName
                        ClassName = $azureFunctionClassName
                        File = $relativePath
                        TriggerType = $triggerType
                        ReturnType = $returnType
                        Parameters = $parameters.Trim()
                    }
                }
                
                # Pattern for [Function(nameof(Class))] - Azure Functions v4+ Isolated Worker
                $functionMatches = [regex]::Matches($content, '\[Function\((?:nameof\()?(\w+)\)?\)\]\s*(?:\[.*?\]\s*)*(?:public|internal|private|protected)?\s*(?:static\s+)?(?:async\s+)?(?:Task<)?(\w+)(?:>)?\s+(\w+)\s*\(([^)]*)\)')
                
                foreach ($funcMatch in $functionMatches) {
                    $functionName = $funcMatch.Groups[1].Value
                    $returnType = $funcMatch.Groups[2].Value
                    $methodName = $funcMatch.Groups[3].Value
                    $parameters = $funcMatch.Groups[4].Value
                    
                    # Determine trigger type
                    $triggerType = "Unknown"
                    if ($parameters -match 'HttpTrigger') { $triggerType = "HTTP" }
                    elseif ($parameters -match 'TimerTrigger') { $triggerType = "Timer" }
                    elseif ($parameters -match 'ServiceBusTrigger') { $triggerType = "ServiceBus" }
                    elseif ($parameters -match 'QueueTrigger') { $triggerType = "Queue" }
                    elseif ($parameters -match 'BlobTrigger') { $triggerType = "Blob" }
                    elseif ($parameters -match 'EventHubTrigger') { $triggerType = "EventHub" }
                    elseif ($parameters -match 'EventGridTrigger') { $triggerType = "EventGrid" }
                    
                    $entryPoints.AzureFunctions += @{
                        Name = $functionName
                        Method = $methodName
                        ClassName = $azureFunctionClassName
                        File = $relativePath
                        TriggerType = $triggerType
                        ReturnType = $returnType
                        Parameters = $parameters.Trim()
                    }
                }
            }
            
            # Message Handlers (MassTransit, NServiceBus, MediatR)
            if ($content -match 'class\s+(\w+)\s*:\s*(?:IConsumer<|IHandleMessages<|IRequestHandler<|INotificationHandler<)(\w+)') {
                $className = $Matches[1]
                $messageType = $Matches[2]
                
                $entryPoints.MessageHandlers += @{
                    Name = $className
                    File = $relativePath
                    MessageType = $messageType
                    HandlerType = if ($content -match 'IConsumer') { "Consumer" } 
                                  elseif ($content -match 'IRequestHandler') { "Command/Query" }
                                  elseif ($content -match 'INotificationHandler') { "Notification" }
                                  else { "MessageHandler" }
                }
            }
            
            # Background Jobs/Hosted Services
            if ($content -match 'class\s+(\w+)\s*:\s*(?:BackgroundService|IHostedService)') {
                $className = $Matches[1]
                
                $entryPoints.BackgroundJobs += @{
                    Name = $className
                    File = $relativePath
                    Type = "HostedService"
                }
            }
            
            # GraphQL Resolvers (HotChocolate)
            if ($content -match 'class\s+(\w+)\s*:\s*ObjectType<(\w+)>') {
                $className = $Matches[1]
                $objectType = $Matches[2]
                
                $entryPoints.GraphQLResolvers += @{
                    Name = $className
                    File = $relativePath
                    ObjectType = $objectType
                }
            }
            
            # SignalR Hubs
            if ($content -match 'class\s+(\w+)\s*:\s*Hub(?:<(\w+)>)?') {
                $className = $Matches[1]
                
                $entryPoints.SignalRHubs += @{
                    Name = $className
                    File = $relativePath
                }
            }
            
            # gRPC Services
            if ($content -match 'class\s+(\w+)\s*:\s*(\w+)\.(\w+)Base') {
                $className = $Matches[1]
                $serviceBase = $Matches[2] + "." + $Matches[3]
                
                if ($serviceBase -like "*Base" -and $content -match 'using Grpc') {
                    $entryPoints.gRPCServices += @{
                        Name = $className
                        File = $relativePath
                        ServiceBase = $serviceBase
                    }
                }
            }
            
            # Minimal API Endpoints (Program.cs / Startup.cs)
            if ($file.Name -eq "Program.cs" -or $file.Name -eq "Startup.cs") {
                $endpointMatches = [regex]::Matches($content, 'app\.Map(Get|Post|Put|Delete|Patch)\("([^"]+)"')
                foreach ($match in $endpointMatches) {
                    $entryPoints.Endpoints += @{
                        HttpVerb = $match.Groups[1].Value
                        Route = $match.Groups[2].Value
                        File = $relativePath
                    }
                }
            }
            
        } catch {
            Write-Warning "Error analyzing $($file.Name): $_"
        }
    }
    
    return $entryPoints
}

function Trace-MethodCalls {
    param(
        [string]$MethodName,
        [string]$ClassName,
        [hashtable]$FileIndex,
        [int]$Depth = 0,
        [int]$MaxDepth = 10,
        [hashtable]$Visited = @{},
        [hashtable]$TypeCache = @{}
    )
    
    if ($Depth -ge $MaxDepth) { 
        return @() 
    }
    
    $key = "$ClassName.$MethodName"
    if ($Visited.ContainsKey($key)) { 
        return @() 
    }
    $Visited[$key] = $true
    
    $calls = @()
    
    # Find the file containing this class
    $classFile = $FileIndex[$ClassName]
    if (-not $classFile) { 
        return $calls 
    }
    
    try {
        $content = Get-Content $classFile -Raw -ErrorAction SilentlyContinue
        if (-not $content) { return $calls }
        
        # Build type cache for this class if not already done
        if (-not $TypeCache.ContainsKey($ClassName)) {
            $typeMap = @{}
            
            # Find all fields (private, protected, internal, public)
            $fieldMatches = [regex]::Matches($content, '(?:private|protected|internal|public)\s+(?:readonly\s+)?(?:(?:I)?(\w+)(?:<[\w,\s<>]+>)?)\s+_?(\w+)\s*[;=]')
            foreach ($match in $fieldMatches) {
                $type = $match.Groups[1].Value
                $varName = $match.Groups[2].Value
                if ($type -and $varName) {
                    $typeMap[$varName] = $type
                }
            }
            
            # Find properties
            $propMatches = [regex]::Matches($content, '(?:private|protected|internal|public)\s+(?:(?:I)?(\w+)(?:<[\w,\s<>]+>)?)\s+(\w+)\s*\{\s*get')
            foreach ($match in $propMatches) {
                $type = $match.Groups[1].Value
                $varName = $match.Groups[2].Value
                if ($type -and $varName) {
                    $typeMap[$varName] = $type
                }
            }
            
            # Find constructor parameters that are likely stored
            $ctorMatches = [regex]::Matches($content, "public\s+$ClassName\s*\([^)]+\)")
            foreach ($ctorMatch in $ctorMatches) {
                $ctorText = $ctorMatch.Value
                $paramMatches = [regex]::Matches($ctorText, '(?:I)?(\w+)(?:<[\w,\s<>]+>)?\s+(\w+)')
                foreach ($paramMatch in $paramMatches) {
                    $type = $paramMatch.Groups[1].Value
                    $varName = $paramMatch.Groups[2].Value
                    if ($type -and $varName -and -not $typeMap.ContainsKey($varName)) {
                        $typeMap[$varName] = $type
                    }
                }
            }
            
            $TypeCache[$ClassName] = $typeMap
        }
        
        # Modified by AI on 11/03/2025. Edit #4.
        # Find the method body - improved extraction that handles nested braces and multi-line signatures
        # Use RegexOptions.Singleline to make . match newlines, allowing multi-line method signatures
        $methodStartPattern = "(?:public|private|protected|internal)\s+(?:static\s+)?(?:async\s+)?(?:Task<)?[\w<>]+(?:>)?\s+$MethodName\s*\("
        $methodStartMatch = [regex]::Match($content, $methodStartPattern, [System.Text.RegularExpressions.RegexOptions]::Singleline)
        
        if (-not $methodStartMatch.Success) {
            Write-Verbose "Method $MethodName not found in $ClassName using pattern"
            return @()
        }
        
        # Find the closing parenthesis of the method signature FIRST to skip over attributes/parameters
        # This prevents finding braces in attribute strings like [HttpTrigger(Route = "...{param}...")]
        $parenCount = 1
        $searchPos = $content.IndexOf('(', $methodStartMatch.Index) + 1
        $closingParenPos = -1
        
        while ($searchPos -lt $content.Length -and $parenCount -gt 0) {
            $char = $content[$searchPos]
            if ($char -eq '(') { $parenCount++ }
            elseif ($char -eq ')') { 
                $parenCount--
                if ($parenCount -eq 0) { $closingParenPos = $searchPos }
            }
            $searchPos++
        }
        
        if ($closingParenPos -lt 0) {
            Write-Verbose "No closing parenthesis found for method signature $ClassName.$MethodName"
            return @()
        }
        
        # Now find the opening brace AFTER the closing parenthesis
        $startPos = $content.IndexOf('{', $closingParenPos)
        if ($startPos -lt 0) {
            Write-Verbose "No opening brace found for $ClassName.$MethodName"
            return @()
        }
        
        # Find matching closing brace
        $braceCount = 1
        $pos = $startPos + 1
        $endPos = -1
        
        while ($pos -lt $content.Length -and $braceCount -gt 0) {
            $char = $content[$pos]
            if ($char -eq '{') { $braceCount++ }
            elseif ($char -eq '}') { $braceCount--; if ($braceCount -eq 0) { $endPos = $pos } }
            $pos++
        }
        
        if ($endPos -gt $startPos) {
            $methodBody = $content.Substring($startPos + 1, $endPos - $startPos - 1)
            Write-Verbose "Extracted method body for $ClassName.$MethodName (length: $($methodBody.Length))"
            
            # Extract method calls - improved pattern
            $callMatches = [regex]::Matches($methodBody, '(?:await\s+)?(?:_?(\w+)|this)\.(\w+)(?:<[^>]+>)?\s*\(')
            
            foreach ($callMatch in $callMatches) {
                $instance = $callMatch.Groups[1].Value
                $calledMethod = $callMatch.Groups[2].Value
                
                # Skip common BCL methods that aren't interesting
                if ($calledMethod -in @('ToString', 'GetHashCode', 'Equals', 'GetType', 'GetEnumerator')) {
                    continue
                }
                
                # Try to resolve the type of the instance
                $calledType = "Unknown"
                if ($instance -and $TypeCache.ContainsKey($ClassName) -and $TypeCache[$ClassName].ContainsKey($instance)) {
                    $calledType = $TypeCache[$ClassName][$instance]
                } elseif ($instance -eq "" -or $instance -eq "this") {
                    # It's a call to a method in the same class
                    $calledType = $ClassName
                }
                
                # Special handling for MediatR Send pattern
                if ($calledMethod -eq "Send") {
                    # Look for pattern: Send(new SomeRequest(...))  
                    # Search in a substring starting from this call
                    $remainingBody = $methodBody.Substring($callMatch.Index)
                    $requestMatch = [regex]::Match($remainingBody, 'Send\s*\(\s*new\s+(\w+)')
                    if ($requestMatch.Success) {
                        $requestType = $requestMatch.Groups[1].Value
                        # Find the handler for this request
                        $handlerType = $requestType -replace 'Request$', 'RequestHandler'
                        if (-not $handlerType.EndsWith('Handler')) {
                            $handlerType = $requestType + "Handler"
                        }
                        
                        $calls += @{
                            From = "$ClassName.$MethodName"
                            To = "$handlerType.Handle"
                            Instance = "MediatR"
                            RequestType = $requestType
                            Depth = $Depth
                        }
                        
                        # Recursively trace into the handler
                        if ($FileIndex.ContainsKey($handlerType)) {
                            $nestedCalls = Trace-MethodCalls -MethodName "Handle" -ClassName $handlerType -FileIndex $FileIndex -Depth ($Depth + 1) -MaxDepth $MaxDepth -Visited $Visited -TypeCache $TypeCache
                            $calls += $nestedCalls
                        } else {
                            Write-Verbose "Handler not found in index: $handlerType (from $ClassName.$MethodName)"
                        }
                        continue
                    }
                }
                
                # Skip if we couldn't resolve and it's a common pattern
                if ($calledType -eq "Unknown" -and $calledMethod -in @('Send', 'Validate', 'Any', 'FirstOrDefaultAsync', 'Where', 'Select', 'ToList', 'Count')) {
                    # These are likely extension methods or LINQ - still track but mark specially
                    $calls += @{
                        From = "$ClassName.$MethodName"
                        To = "$calledMethod (extension/LINQ)"
                        Instance = $instance
                        Depth = $Depth
                    }
                    continue
                }
                
                $calls += @{
                    From = "$ClassName.$MethodName"
                    To = "$calledType.$calledMethod"
                    Instance = $instance
                    Depth = $Depth
                }
                
                # Recursive trace
                if ($calledType -ne "Unknown" -and $FileIndex.ContainsKey($calledType)) {
                    $nestedCalls = Trace-MethodCalls -MethodName $calledMethod -ClassName $calledType -FileIndex $FileIndex -Depth ($Depth + 1) -MaxDepth $MaxDepth -Visited $Visited -TypeCache $TypeCache
                    $calls += $nestedCalls
                }
            }
            
            # Extract database calls
            $dbCalls = [regex]::Matches($methodBody, '\.(ExecuteAsync|QueryAsync|Query|Execute|FirstOrDefaultAsync|ToListAsync|SaveChangesAsync|AddAsync|UpdateAsync|RemoveAsync)\s*\(')
            if ($dbCalls.Count -gt 0) {
                $calls += @{
                    From = "$ClassName.$MethodName"
                    To = "[Database]"
                    Type = "Database"
                    Depth = $Depth
                }
            }
            
            # Extract external service calls
            $httpCalls = [regex]::Matches($methodBody, '\.(GetAsync|PostAsync|PutAsync|DeleteAsync|SendAsync|GetStringAsync)\s*\(')
            if ($httpCalls.Count -gt 0) {
                $calls += @{
                    From = "$ClassName.$MethodName"
                    To = "[HTTP Call]"
                    Type = "HTTP"
                    Depth = $Depth
                }
            }
        }
        
    } catch {
        Write-Warning "Error tracing calls in $ClassName.$MethodName : $_"
    }
    
    # Ensure we always return an array, even if empty or single item
    return @() + $calls
}

function Build-FileIndex {
    Write-Host "  📑 Building file index..." -ForegroundColor Gray
    
    $index = @{}
    $csFiles = Get-CSharpFiles
    
    foreach ($file in $csFiles) {
        try {
            $content = Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue
            if (-not $content) { continue }
            
            # Extract all class names
            $classMatches = [regex]::Matches($content, '(?:public|internal|private|protected)\s+(?:static\s+)?(?:partial\s+)?class\s+(\w+)')
            foreach ($match in $classMatches) {
                $className = $match.Groups[1].Value
                $index[$className] = $file.FullName
            }
            
        } catch {
            Write-Warning "Error indexing $($file.Name): $_"
        }
    }
    
    Write-Host "    Indexed $($index.Count) classes" -ForegroundColor Gray
    return $index
}

function Get-MaxCallDepth {
    param($CallArray)
    
    if (-not $CallArray -or $CallArray.Count -eq 0) { return 0 }
    
    $maxDepth = 0
    foreach ($call in $CallArray) {
        if ($call.Depth -gt $maxDepth) {
            $maxDepth = $call.Depth
        }
    }
    
    return $maxDepth
}

function Generate-DataFlows {
    param(
        $EntryPoints, 
        $FileIndex,
        [int]$MaxDepth = 10
    )
    
    Write-Host "  🌊 Tracing data flows..." -ForegroundColor Gray
    
    $flows = @()
    $globalTypeCache = @{}
    
    # Trace from Controllers
    foreach ($controller in $EntryPoints.Controllers) {
        foreach ($endpoint in $controller.Endpoints) {
            $visited = @{}
            $calls = Trace-MethodCalls -MethodName $endpoint.Method -ClassName $controller.Name -FileIndex $FileIndex -MaxDepth $MaxDepth -Visited $visited -TypeCache $globalTypeCache
            
            $flowDepth = Get-MaxCallDepth -CallArray $calls
            
            $flows += @{
                EntryPoint = "$($controller.Name).$($endpoint.Method)"
                Type = "Controller"
                Route = "$($endpoint.HttpVerb) $($endpoint.Route)"
                CallChain = $calls
                Depth = $flowDepth
            }
        }
    }
    
    # Trace from Azure Functions
    foreach ($function in $EntryPoints.AzureFunctions) {
        $visited = @{}
        $functionClassName = if ($function.ClassName) { $function.ClassName } else { "FunctionClass" }
        $calls = Trace-MethodCalls -MethodName $function.Method -ClassName $functionClassName -FileIndex $FileIndex -MaxDepth $MaxDepth -Visited $visited -TypeCache $globalTypeCache
        
        $flowDepth = Get-MaxCallDepth -CallArray $calls
        
        $flows += @{
            EntryPoint = $function.Name
            Type = "AzureFunction"
            Trigger = $function.TriggerType
            CallChain = $calls
            Depth = $flowDepth
        }
    }
    
    # Trace from Message Handlers
    foreach ($handler in $EntryPoints.MessageHandlers) {
        $visited = @{}
        $calls = Trace-MethodCalls -MethodName "Handle" -ClassName $handler.Name -FileIndex $FileIndex -MaxDepth $MaxDepth -Visited $visited -TypeCache $globalTypeCache
        
        $flowDepth = Get-MaxCallDepth -CallArray $calls
        
        $flows += @{
            EntryPoint = $handler.Name
            Type = "MessageHandler"
            MessageType = $handler.MessageType
            CallChain = $calls
            Depth = $flowDepth
        }
    }
    
    return $flows
}

function Format-HierarchicalFlow {
    param($Flow)
    
    $output = @()
    $output += "### $($Flow.EntryPoint)"
    $output += "**Type:** $($Flow.Type)"
    
    if ($Flow.Route) { $output += "**Route:** $($Flow.Route)" }
    if ($Flow.Trigger) { $output += "**Trigger:** $($Flow.Trigger)" }
    if ($Flow.MessageType) { $output += "**Message:** $($Flow.MessageType)" }
    
    $output += ""
    $output += "**Call Flow:**"
    $output += "``````"
    $output += $Flow.EntryPoint
    
    # Group calls by depth and format hierarchically
    $callsByDepth = $Flow.CallChain | Group-Object -Property Depth | Sort-Object Name
    
    foreach ($depthGroup in $callsByDepth) {
        $indent = "  " * ($depthGroup.Name + 1)
        foreach ($call in $depthGroup.Group) {
            if ($call.Type -eq "Database") {
                $output += "$indent└─> [DB] $($call.To)"
            } elseif ($call.Type -eq "HTTP") {
                $output += "$indent└─> [HTTP] $($call.To)"
            } else {
                $output += "$indent└─> $($call.To)"
            }
        }
    }
    
    $output += "``````"
    $output += ""
    
    return $output -join "`n"
}

# Main Analysis
$analysis = @{
    Repository = Split-Path $RepositoryPath -Leaf
    AnalyzedAt = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    EntryPoints = @{}
    DataFlows = @()
    Statistics = @{}
}

# Find all entry points
$analysis.EntryPoints = Find-EntryPoints

# Build class/file index
$fileIndex = Build-FileIndex

# Generated by AI on 10/31/2024
# Generate data flows
$analysis.DataFlows = Generate-DataFlows -EntryPoints $analysis.EntryPoints -FileIndex $fileIndex -MaxDepth $MaxDepth

# Calculate statistics
$analysis.Statistics = @{
    TotalEntryPoints = (
        $analysis.EntryPoints.Controllers.Count + 
        $analysis.EntryPoints.AzureFunctions.Count + 
        $analysis.EntryPoints.MessageHandlers.Count +
        $analysis.EntryPoints.BackgroundJobs.Count +
        $analysis.EntryPoints.GraphQLResolvers.Count +
        $analysis.EntryPoints.SignalRHubs.Count +
        $analysis.EntryPoints.gRPCServices.Count +
        $analysis.EntryPoints.Endpoints.Count
    )
    TotalDataFlows = $analysis.DataFlows.Count
    MaxCallDepth = ($analysis.DataFlows | Measure-Object -Property Depth -Maximum).Maximum
    TotalClassesIndexed = $fileIndex.Count
}

Write-Host "✅ Analysis complete!" -ForegroundColor Green
Write-Host "  Entry Points: $($analysis.Statistics.TotalEntryPoints)" -ForegroundColor Gray
Write-Host "  Data Flows: $($analysis.Statistics.TotalDataFlows)" -ForegroundColor Gray
Write-Host "  Max Call Depth: $($analysis.Statistics.MaxCallDepth)" -ForegroundColor Gray

return $analysis
