#!/usr/bin/env pwsh
# Generated by AI on 10/31/2024
<#
.SYNOPSIS
    DTO and Key Class Extractor

.DESCRIPTION
    Identifies and catalogs all DTOs, request/response models, domain entities,
    view models, and other key business classes. Extracts properties, relationships,
    and inheritance hierarchies.

.PARAMETER RepositoryPath
    Path to repository to analyze

.PARAMETER IncludeTests
    Include test classes in analysis

.EXAMPLE
    .\Extract-DTOsAndClasses.ps1 -RepositoryPath "C:\MyRepo"
#>

param(
    [string]$RepositoryPath = ".",
    [switch]$IncludeTests = $false
)

$RepositoryPath = Resolve-Path $RepositoryPath

Write-Host "📦 Extracting DTOs and Key Classes..." -ForegroundColor Cyan

function Get-CSharpFiles {
    return Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*.cs" -ErrorAction SilentlyContinue | 
        Where-Object { 
            $_.FullName -notlike "*\bin\*" -and 
            $_.FullName -notlike "*\obj\*" -and
            ($IncludeTests -or ($_.Name -notlike "*test*" -and $_.Name -notlike "*Test*"))
        }
}

function Extract-ClassInfo {
    param([string]$FilePath, [string]$Content)
    
    $classes = @()
    $relativePath = $FilePath.Replace($RepositoryPath, "").TrimStart('\', '/')
    
    # Extract namespace
    $namespaceMatch = [regex]::Match($Content, 'namespace\s+([\w.]+)')
    $namespace = if ($namespaceMatch.Success) { $namespaceMatch.Groups[1].Value } else { "Global" }
    
    # Find all class definitions
    $classPattern = '(?:public|internal|private|protected)\s+(?:static\s+)?(?:partial\s+)?(?:abstract\s+)?(class|interface|enum|record)\s+(\w+)(?:<([^>]+)>)?(?:\s*:\s*([^{]+))?'
    $classMatches = [regex]::Matches($Content, $classPattern)
    
    foreach ($match in $classMatches) {
        $classType = $match.Groups[1].Value
        $className = $match.Groups[2].Value
        $genericParams = $match.Groups[3].Value
        $inheritance = $match.Groups[4].Value.Trim()
        
        # Classify the class
        $category = Get-ClassCategory -ClassName $className -Content $Content -Inheritance $inheritance
        
        # Extract properties
        $properties = Extract-Properties -Content $Content -ClassName $className
        
        # Extract methods (for interfaces and key classes)
        $methods = Extract-Methods -Content $Content -ClassName $className -ClassType $classType
        
        # Extract attributes/annotations
        $attributes = Extract-ClassAttributes -Content $Content -ClassName $className
        
        $classInfo = @{
            Name = $className
            Type = $classType
            Category = $category
            Namespace = $namespace
            File = $relativePath
            GenericParameters = if ($genericParams) { $genericParams } else { $null }
            BaseClass = Get-BaseClass -Inheritance $inheritance
            Interfaces = Get-Interfaces -Inheritance $inheritance
            Properties = $properties
            Methods = $methods
            Attributes = $attributes
            IsDTO = $category -in @("DTO", "Request", "Response", "ViewModel", "Command", "Query", "Event")
            IsDomainEntity = $category -in @("Entity", "Aggregate", "ValueObject")
        }
        
        $classes += $classInfo
    }
    
    return $classes
}

function Get-ClassCategory {
    param([string]$ClassName, [string]$Content, [string]$Inheritance)
    
    # Pattern-based classification
    if ($ClassName -match '(Dto|DTO)$') { return "DTO" }
    if ($ClassName -match 'Request$') { return "Request" }
    if ($ClassName -match 'Response$') { return "Response" }
    if ($ClassName -match 'ViewModel$') { return "ViewModel" }
    if ($ClassName -match 'Command$') { return "Command" }
    if ($ClassName -match 'Query$') { return "Query" }
    if ($ClassName -match 'Event$') { return "Event" }
    if ($ClassName -match 'Message$') { return "Message" }
    if ($ClassName -match 'Model$') { return "Model" }
    if ($ClassName -match 'Entity$') { return "Entity" }
    if ($ClassName -match 'Service$') { return "Service" }
    if ($ClassName -match 'Repository$') { return "Repository" }
    if ($ClassName -match 'Controller$') { return "Controller" }
    if ($ClassName -match 'Handler$') { return "Handler" }
    if ($ClassName -match 'Provider$') { return "Provider" }
    if ($ClassName -match 'Factory$') { return "Factory" }
    if ($ClassName -match 'Builder$') { return "Builder" }
    if ($ClassName -match 'Mapper$') { return "Mapper" }
    if ($ClassName -match 'Validator$') { return "Validator" }
    if ($ClassName -match 'Configuration$') { return "Configuration" }
    if ($ClassName -match 'Options$') { return "Options" }
    if ($ClassName -match 'Settings$') { return "Settings" }
    if ($ClassName -match 'Helper$') { return "Helper" }
    if ($ClassName -match 'Utility$') { return "Utility" }
    if ($ClassName -match 'Extension$') { return "Extension" }
    if ($ClassName -match 'Exception$') { return "Exception" }
    
    # Inheritance-based classification
    if ($Inheritance -match 'Controller|ControllerBase|ApiController') { return "Controller" }
    if ($Inheritance -match 'IEntity|EntityBase|Entity<') { return "Entity" }
    if ($Inheritance -match 'ValueObject') { return "ValueObject" }
    if ($Inheritance -match 'AggregateRoot') { return "Aggregate" }
    if ($Inheritance -match 'DbContext') { return "DbContext" }
    if ($Inheritance -match 'IRepository|Repository<') { return "Repository" }
    if ($Inheritance -match 'IService') { return "Service" }
    if ($Inheritance -match 'IMapper') { return "Mapper" }
    if ($Inheritance -match 'IValidator|AbstractValidator<') { return "Validator" }
    if ($Inheritance -match 'IRequestHandler|INotificationHandler|IConsumer') { return "Handler" }
    if ($Inheritance -match 'Hub<|Hub$') { return "SignalRHub" }
    if ($Inheritance -match 'BackgroundService|IHostedService') { return "BackgroundService" }
    
    # Attribute-based classification
    if ($Content -match "\[Table\(`"$ClassName`"\)\]" -or $Content -match "\[Entity\]") { return "Entity" }
    if ($Content -match "\[ApiController\]") { return "Controller" }
    if ($Content -match "\[FunctionName\]") { return "AzureFunction" }
    
    # Default
    return "Class"
}

function Extract-Properties {
    param([string]$Content, [string]$ClassName)
    
    $properties = @()
    
    # Find the class body
    $classBodyPattern = "(?:class|record)\s+$ClassName(?:<[^>]+>)?(?:\s*:\s*[^{]+)?\s*\{([^}]+(?:\{[^}]*\}[^}]*)*)\}"
    $classBodyMatch = [regex]::Match($Content, $classBodyPattern, [System.Text.RegularExpressions.RegexOptions]::Singleline)
    
    if ($classBodyMatch.Success) {
        $classBody = $classBodyMatch.Groups[1].Value
        
        # Extract properties
        $propertyPattern = '(?:public|internal|protected|private)\s+(?:virtual\s+)?(?:required\s+)?(?:static\s+)?([^\s]+(?:<[^>]+>)?)\s+(\w+)\s*\{\s*(?:get;)?(?:\s*set;)?(?:\s*init;)?\s*\}'
        $propertyMatches = [regex]::Matches($classBody, $propertyPattern)
        
        foreach ($propMatch in $propertyMatches) {
            $propertyType = $propMatch.Groups[1].Value
            $propertyName = $propMatch.Groups[2].Value
            
            # Extract attributes for this property
            $attributePattern = "\[([^\]]+)\]\s+(?:public|internal|protected|private)\s+(?:virtual\s+)?(?:required\s+)?$propertyType\s+$propertyName"
            $attributeMatches = [regex]::Matches($classBody, $attributePattern)
            
            $propertyAttributes = @()
            foreach ($attrMatch in $attributeMatches) {
                $propertyAttributes += $attrMatch.Groups[1].Value
            }
            
            # Determine if property is nullable
            $isNullable = $propertyType -match '\?$' -or $propertyType -match 'Nullable<'
            
            # Check for required attribute
            $isRequired = $classBody -match "required\s+$propertyType\s+$propertyName" -or 
                          $propertyAttributes -match 'Required'
            
            $properties += @{
                Name = $propertyName
                Type = $propertyType
                IsNullable = $isNullable
                IsRequired = $isRequired
                Attributes = $propertyAttributes
            }
        }
    }
    
    return $properties
}

function Extract-Methods {
    param([string]$Content, [string]$ClassName, [string]$ClassType)
    
    $methods = @()
    
    # Only extract methods for interfaces and key classes
    if ($ClassType -ne "interface" -and $ClassName -notmatch '(Service|Repository|Handler|Provider|Factory)$') {
        return $methods
    }
    
    # Find the class body
    $classBodyPattern = "(?:$ClassType)\s+$ClassName(?:<[^>]+>)?(?:\s*:\s*[^{]+)?\s*\{([^}]+(?:\{[^}]*\}[^}]*)*)\}"
    $classBodyMatch = [regex]::Match($Content, $classBodyPattern, [System.Text.RegularExpressions.RegexOptions]::Singleline)
    
    if ($classBodyMatch.Success) {
        $classBody = $classBodyMatch.Groups[1].Value
        
        # Extract method signatures
        $methodPattern = '(?:public|internal|protected)\s+(?:static\s+)?(?:async\s+)?(?:virtual\s+)?([^\s]+(?:<[^>]+>)?)\s+(\w+)\s*\(([^)]*)\)'
        $methodMatches = [regex]::Matches($classBody, $methodPattern)
        
        foreach ($methodMatch in $methodMatches) {
            $returnType = $methodMatch.Groups[1].Value
            $methodName = $methodMatch.Groups[2].Value
            $parameters = $methodMatch.Groups[3].Value.Trim()
            
            $methods += @{
                Name = $methodName
                ReturnType = $returnType
                Parameters = $parameters
            }
        }
    }
    
    return $methods
}

function Extract-ClassAttributes {
    param([string]$Content, [string]$ClassName)
    
    $attributes = @()
    
    # Find attributes on the class
    $attributePattern = "\[([^\]]+)\]\s+(?:public|internal|private|protected)\s+(?:static\s+)?(?:partial\s+)?(?:abstract\s+)?(?:class|interface|enum|record)\s+$ClassName"
    $attributeMatches = [regex]::Matches($Content, $attributePattern)
    
    foreach ($match in $attributeMatches) {
        $attributes += $match.Groups[1].Value
    }
    
    return $attributes
}

function Get-BaseClass {
    param([string]$Inheritance)
    
    if (-not $Inheritance) { return $null }
    
    $parts = $Inheritance -split ',' | ForEach-Object { $_.Trim() }
    
    # First item is usually the base class (if it's a class, not an interface)
    $first = $parts[0]
    if ($first -and $first -notmatch '^I[A-Z]') {
        return $first
    }
    
    return $null
}

function Get-Interfaces {
    param([string]$Inheritance)
    
    if (-not $Inheritance) { return @() }
    
    $parts = $Inheritance -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ }
    
    # Interfaces typically start with 'I' followed by uppercase letter
    return @($parts | Where-Object { $_ -match '^I[A-Z]' })
}

function Group-ClassesByCategory {
    param($Classes)
    
    $grouped = @{
        DTOs = @()
        Requests = @()
        Responses = @()
        ViewModels = @()
        Commands = @()
        Queries = @()
        Events = @()
        Entities = @()
        Aggregates = @()
        ValueObjects = @()
        Services = @()
        Repositories = @()
        Controllers = @()
        Handlers = @()
        Validators = @()
        Mappers = @()
        Configurations = @()
        AzureFunctions = @()
        SignalRHubs = @()
        BackgroundServices = @()
        Other = @()
    }
    
    foreach ($class in $Classes) {
        switch ($class.Category) {
            "DTO" { $grouped.DTOs += $class }
            "Request" { $grouped.Requests += $class }
            "Response" { $grouped.Responses += $class }
            "ViewModel" { $grouped.ViewModels += $class }
            "Command" { $grouped.Commands += $class }
            "Query" { $grouped.Queries += $class }
            "Event" { $grouped.Events += $class }
            "Entity" { $grouped.Entities += $class }
            "Aggregate" { $grouped.Aggregates += $class }
            "ValueObject" { $grouped.ValueObjects += $class }
            "Service" { $grouped.Services += $class }
            "Repository" { $grouped.Repositories += $class }
            "Controller" { $grouped.Controllers += $class }
            "Handler" { $grouped.Handlers += $class }
            "Validator" { $grouped.Validators += $class }
            "Mapper" { $grouped.Mappers += $class }
            "Configuration" { $grouped.Configurations += $class }
            "AzureFunction" { $grouped.AzureFunctions += $class }
            "SignalRHub" { $grouped.SignalRHubs += $class }
            "BackgroundService" { $grouped.BackgroundServices += $class }
            default { $grouped.Other += $class }
        }
    }
    
    return $grouped
}

function Generate-ClassDiagram {
    param($Classes)
    
    $diagram = @()
    $diagram += "## Class Relationships (Mermaid)"
    $diagram += ""
    $diagram += "``````mermaid"
    $diagram += "classDiagram"
    
    # Add key classes with relationships
    $keyClasses = $Classes | Where-Object { 
        $_.Category -in @("Entity", "Aggregate", "DTO", "Request", "Response", "Command", "Query", "Event") 
    } | Select-Object -First 50  # Limit to prevent overwhelming diagrams
    
    foreach ($class in $keyClasses) {
        # Add class with properties
        $diagram += "    class $($class.Name) {"
        foreach ($prop in ($class.Properties | Select-Object -First 10)) {
            $diagram += "        $($prop.Type) $($prop.Name)"
        }
        $diagram += "    }"
        
        # Add inheritance
        if ($class.BaseClass) {
            $diagram += "    $($class.BaseClass) <|-- $($class.Name)"
        }
        
        # Add interface implementations
        foreach ($interface in $class.Interfaces) {
            $diagram += "    $interface <|.. $($class.Name)"
        }
    }
    
    $diagram += "``````"
    $diagram += ""
    
    return $diagram -join "`n"
}

function Format-ClassCatalog {
    param($GroupedClasses)
    
    $output = @()
    $output += "# Class Catalog"
    $output += ""
    $output += "Complete listing of all DTOs, entities, and key classes in the repository."
    $output += ""
    
    foreach ($categoryName in $GroupedClasses.Keys | Sort-Object) {
        $classes = $GroupedClasses[$categoryName]
        if ($classes.Count -eq 0) { continue }
        
        $output += "## $categoryName ($($classes.Count))"
        $output += ""
        
        foreach ($class in ($classes | Sort-Object Name)) {
            $output += "### $($class.Name)"
            $output += "**Namespace:** ``$($class.Namespace)``  "
            $output += "**File:** ``$($class.File)``  "
            $output += "**Type:** $($class.Type)"
            
            if ($class.BaseClass) {
                $output += "**Inherits:** ``$($class.BaseClass)``"
            }
            
            if ($class.Interfaces -and $class.Interfaces.Count -gt 0) {
                $output += "**Implements:** " + (($class.Interfaces | ForEach-Object { "``$_``" }) -join ", ")
            }
            
            if ($class.Attributes -and $class.Attributes.Count -gt 0) {
                $output += "**Attributes:** " + (($class.Attributes | ForEach-Object { "``[$_]``" }) -join " ")
            }
            
            if ($class.Properties -and $class.Properties.Count -gt 0) {
                $output += ""
                $output += "**Properties:**"
                $output += ""
                $output += "| Property | Type | Required | Nullable | Attributes |"
                $output += "|----------|------|----------|----------|------------|"
                
                foreach ($prop in $class.Properties) {
                    $required = if ($prop.IsRequired) { "✅" } else { "❌" }
                    $nullable = if ($prop.IsNullable) { "✅" } else { "❌" }
                    $attrs = if ($prop.Attributes) { ($prop.Attributes -join ", ") } else { "-" }
                    $output += "| ``$($prop.Name)`` | ``$($prop.Type)`` | $required | $nullable | $attrs |"
                }
            }
            
            if ($class.Methods -and $class.Methods.Count -gt 0) {
                $output += ""
                $output += "**Methods:**"
                foreach ($method in $class.Methods) {
                    $output += "- ``$($method.ReturnType) $($method.Name)($($method.Parameters))``"
                }
            }
            
            $output += ""
        }
    }
    
    return $output -join "`n"
}

# Main Extraction
Write-Host "  📄 Scanning C# files..." -ForegroundColor Gray
$csFiles = Get-CSharpFiles

$allClasses = @()
$fileCount = 0

foreach ($file in $csFiles) {
    $fileCount++
    if ($fileCount % 10 -eq 0) {
        Write-Host "    Processed $fileCount files..." -ForegroundColor Gray
    }
    
    try {
        $content = Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue
        if (-not $content) { continue }
        
        $classes = Extract-ClassInfo -FilePath $file.FullName -Content $content
        $allClasses += $classes
        
    } catch {
        Write-Warning "Error processing $($file.Name): $_"
    }
}

Write-Host "  📊 Categorizing classes..." -ForegroundColor Gray
$groupedClasses = Group-ClassesByCategory -Classes $allClasses

$analysis = @{
    Repository = Split-Path $RepositoryPath -Leaf
    AnalyzedAt = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    TotalClasses = $allClasses.Count
    TotalFiles = $fileCount
    Categories = @{}
    Classes = $allClasses
    GroupedClasses = $groupedClasses
}

# Calculate statistics per category
foreach ($category in $groupedClasses.Keys) {
    $count = $groupedClasses[$category].Count
    if ($count -gt 0) {
        $analysis.Categories[$category] = $count
    }
}

Write-Host "✅ Extraction complete!" -ForegroundColor Green
Write-Host "  Total Classes: $($allClasses.Count)" -ForegroundColor Gray
Write-Host "  DTOs: $($groupedClasses.DTOs.Count)" -ForegroundColor Gray
Write-Host "  Entities: $($groupedClasses.Entities.Count)" -ForegroundColor Gray
Write-Host "  Services: $($groupedClasses.Services.Count)" -ForegroundColor Gray
Write-Host "  Controllers: $($groupedClasses.Controllers.Count)" -ForegroundColor Gray

return $analysis
