#!/usr/bin/env pwsh
# Generated by AI on 10/31/2024
<#
.SYNOPSIS
    Intelligent Repository Tagging System

.DESCRIPTION
    Automatically generates relevant tags based on detected patterns, frameworks,
    architectural styles, business domains, and technical characteristics.
    Provides both technical and business-oriented tags.

.PARAMETER RepositoryPath
    Path to repository to analyze

.PARAMETER Analysis
    Pre-computed analysis data (from business logic or DTO extraction)

.EXAMPLE
    .\Generate-RepositoryTags.ps1 -RepositoryPath "C:\MyRepo"
#>

param(
    [string]$RepositoryPath = ".",
    [hashtable]$Analysis = $null
)

$RepositoryPath = Resolve-Path $RepositoryPath

Write-Host "🏷️  Generating Intelligent Tags..." -ForegroundColor Cyan

function Detect-FrameworkTags {
    Write-Host "  🔍 Detecting frameworks..." -ForegroundColor Gray
    
    $tags = New-Object System.Collections.Generic.HashSet[string]
    
    # Scan for project files
    $csprojFiles = Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*.csproj" -ErrorAction SilentlyContinue | 
        Where-Object { $_.FullName -notlike "*\bin\*" -and $_.FullName -notlike "*\obj\*" }
    
    foreach ($file in $csprojFiles) {
        $content = Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue
        if (-not $content) { continue }
        
        # .NET Version Tags
        if ($content -match 'net8\.0') { [void]$tags.Add(".NET 8") }
        if ($content -match 'net7\.0') { [void]$tags.Add(".NET 7") }
        if ($content -match 'net6\.0') { [void]$tags.Add(".NET 6") }
        if ($content -match 'netstandard2\.[01]') { [void]$tags.Add(".NET Standard") }
        if ($content -match 'net4[78]') { [void]$tags.Add(".NET Framework") }
        
        # Framework Tags
        if ($content -match 'Microsoft\.AspNetCore') { [void]$tags.Add("ASP.NET Core") }
        if ($content -match 'Microsoft\.Azure\.Functions') { [void]$tags.Add("Azure Functions") }
        if ($content -match 'Microsoft\.Azure\.WebJobs') { [void]$tags.Add("Azure WebJobs") }
        if ($content -match 'MassTransit') { [void]$tags.Add("MassTransit") }
        if ($content -match 'MediatR') { [void]$tags.Add("MediatR") }
        if ($content -match 'AutoMapper') { [void]$tags.Add("AutoMapper") }
        if ($content -match 'Swashbuckle') { [void]$tags.Add("Swagger") }
        if ($content -match 'EntityFrameworkCore') { [void]$tags.Add("Entity Framework Core") }
        if ($content -match 'Dapper') { [void]$tags.Add("Dapper") }
        if ($content -match 'Hangfire') { [void]$tags.Add("Hangfire") }
        if ($content -match 'Quartz') { [void]$tags.Add("Quartz.NET") }
        if ($content -match 'Polly') { [void]$tags.Add("Polly") }
        if ($content -match 'Serilog') { [void]$tags.Add("Serilog") }
        if ($content -match 'NLog') { [void]$tags.Add("NLog") }
        if ($content -match 'FluentValidation') { [void]$tags.Add("FluentValidation") }
        if ($content -match 'xunit') { [void]$tags.Add("xUnit") }
        if ($content -match 'NUnit') { [void]$tags.Add("NUnit") }
        if ($content -match 'Moq') { [void]$tags.Add("Moq") }
        if ($content -match 'SignalR') { [void]$tags.Add("SignalR") }
        if ($content -match 'GraphQL|HotChocolate') { [void]$tags.Add("GraphQL") }
        if ($content -match 'Grpc') { [void]$tags.Add("gRPC") }
        if ($content -match 'IdentityServer') { [void]$tags.Add("IdentityServer") }
        if ($content -match 'Auth0') { [void]$tags.Add("Auth0") }
    }
    
    # Node.js packages
    $packageJsonFiles = Get-ChildItem -Path $RepositoryPath -Recurse -Filter "package.json" -ErrorAction SilentlyContinue | 
        Where-Object { $_.FullName -notlike "*\node_modules\*" }
    
    foreach ($file in $packageJsonFiles) {
        $content = Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue
        if (-not $content) { continue }
        
        if ($content -match '"react"') { [void]$tags.Add("React") }
        if ($content -match '"vue"') { [void]$tags.Add("Vue.js") }
        if ($content -match '"angular"') { [void]$tags.Add("Angular") }
        if ($content -match '"next"') { [void]$tags.Add("Next.js") }
        if ($content -match '"express"') { [void]$tags.Add("Express.js") }
        if ($content -match '"typescript"') { [void]$tags.Add("TypeScript") }
        if ($content -match '"webpack"') { [void]$tags.Add("Webpack") }
        if ($content -match '"jest"') { [void]$tags.Add("Jest") }
    }
    
    return @($tags | Sort-Object)
}

function Detect-ArchitectureTags {
    Write-Host "  🏗️  Detecting architecture patterns..." -ForegroundColor Gray
    
    $tags = New-Object System.Collections.Generic.HashSet[string]
    
    $csFiles = Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*.cs" -ErrorAction SilentlyContinue | 
        Where-Object { $_.FullName -notlike "*\bin\*" -and $_.FullName -notlike "*\obj\*" } |
        Select-Object -First 100  # Sample for performance
    
    $hasControllers = $false
    $hasRepositories = $false
    $hasServices = $false
    $hasHandlers = $false
    $hasCommands = $false
    $hasQueries = $false
    $hasEvents = $false
    $hasAggregates = $false
    $hasDomainModels = $false
    
    foreach ($file in $csFiles) {
        $content = Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue
        if (-not $content) { continue }
        
        if ($content -match 'Controller|ApiController|ControllerBase') { $hasControllers = $true }
        if ($content -match 'class\s+\w+Repository|IRepository<') { $hasRepositories = $true }
        if ($content -match 'class\s+\w+Service|IService') { $hasServices = $true }
        if ($content -match 'IRequestHandler|INotificationHandler|IConsumer') { $hasHandlers = $true }
        if ($content -match 'class\s+\w+Command') { $hasCommands = $true }
        if ($content -match 'class\s+\w+Query') { $hasQueries = $true }
        if ($content -match 'class\s+\w+Event|DomainEvent') { $hasEvents = $true }
        if ($content -match 'AggregateRoot') { $hasAggregates = $true }
        if ($content -match 'namespace.*\.Domain\b') { $hasDomainModels = $true }
    }
    
    # Architecture pattern detection
    if ($hasControllers -and $hasServices -and $hasRepositories) {
        [void]$tags.Add("Layered Architecture")
        [void]$tags.Add("N-Tier")
    }
    
    if ($hasCommands -and $hasQueries -and $hasHandlers) {
        [void]$tags.Add("CQRS")
    }
    
    if ($hasAggregates -and $hasDomainModels -and $hasEvents) {
        [void]$tags.Add("Domain-Driven Design")
        [void]$tags.Add("DDD")
    }
    
    if ($hasEvents -and $hasHandlers) {
        [void]$tags.Add("Event-Driven")
    }
    
    if ($hasRepositories) {
        [void]$tags.Add("Repository Pattern")
    }
    
    # Check for clean architecture indicators
    $hasCleanArchDirs = (Get-ChildItem -Path $RepositoryPath -Directory -ErrorAction SilentlyContinue | 
        Where-Object { $_.Name -match '^(Domain|Application|Infrastructure|Presentation|API)$' }).Count -ge 3
    
    if ($hasCleanArchDirs) {
        [void]$tags.Add("Clean Architecture")
    }
    
    # Microservices indicators
    $hasDockerfile = Test-Path (Join-Path $RepositoryPath "Dockerfile")
    $hasDockerCompose = Test-Path (Join-Path $RepositoryPath "docker-compose.yml")
    $hasK8s = (Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*.yaml" -ErrorAction SilentlyContinue | 
        Where-Object { $_.Name -match 'deployment|service|ingress' }).Count -gt 0
    
    if ($hasDockerfile -or $hasDockerCompose) {
        [void]$tags.Add("Containerized")
        [void]$tags.Add("Docker")
    }
    
    if ($hasK8s) {
        [void]$tags.Add("Kubernetes")
    }
    
    $projectCount = (Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*.csproj" -ErrorAction SilentlyContinue | 
        Where-Object { $_.FullName -notlike "*\bin\*" }).Count
    
    if ($projectCount -gt 5) {
        [void]$tags.Add("Microservices")
    }
    
    return @($tags | Sort-Object)
}

function Detect-CloudTags {
    Write-Host "  ☁️  Detecting cloud services..." -ForegroundColor Gray
    
    $tags = New-Object System.Collections.Generic.HashSet[string]
    
    # Check for Azure
    $azureFiles = Get-ChildItem -Path $RepositoryPath -Recurse -Include "*.cs", "*.json", "*.yml", "*.yaml" -ErrorAction SilentlyContinue | 
        Where-Object { $_.FullName -notlike "*\node_modules\*" -and $_.FullName -notlike "*\bin\*" } |
        Select-Object -First 50
    
    foreach ($file in $azureFiles) {
        $content = Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue
        if (-not $content) { continue }
        
        # Azure Services
        if ($content -match 'Azure') { [void]$tags.Add("Microsoft Azure") }
        if ($content -match 'Azure\.Storage|BlobServiceClient') { [void]$tags.Add("Azure Blob Storage") }
        if ($content -match 'Azure\.ServiceBus|ServiceBusClient') { [void]$tags.Add("Azure Service Bus") }
        if ($content -match 'Azure\.Messaging\.EventHubs') { [void]$tags.Add("Azure Event Hubs") }
        if ($content -match 'Azure\.Messaging\.EventGrid') { [void]$tags.Add("Azure Event Grid") }
        if ($content -match 'Azure\.Data\.Tables') { [void]$tags.Add("Azure Table Storage") }
        if ($content -match 'Azure\.Cosmos') { [void]$tags.Add("Azure Cosmos DB") }
        if ($content -match 'Azure\.KeyVault') { [void]$tags.Add("Azure Key Vault") }
        if ($content -match 'ApplicationInsights') { [void]$tags.Add("Application Insights") }
        if ($content -match 'Azure\.Identity') { [void]$tags.Add("Azure AD") }
        if ($content -match 'Microsoft\.Graph') { [void]$tags.Add("Microsoft Graph") }
        
        # AWS Services
        if ($content -match 'Amazon\.|AWSSDK') { [void]$tags.Add("AWS") }
        if ($content -match 'Amazon\.S3') { [void]$tags.Add("AWS S3") }
        if ($content -match 'Amazon\.Lambda') { [void]$tags.Add("AWS Lambda") }
        if ($content -match 'Amazon\.DynamoDB') { [void]$tags.Add("AWS DynamoDB") }
        if ($content -match 'Amazon\.SQS') { [void]$tags.Add("AWS SQS") }
        if ($content -match 'Amazon\.SNS') { [void]$tags.Add("AWS SNS") }
        
        # GCP Services
        if ($content -match 'Google\.Cloud') { [void]$tags.Add("Google Cloud") }
    }
    
    return @($tags | Sort-Object)
}

function Detect-DatabaseTags {
    Write-Host "  💾 Detecting databases..." -ForegroundColor Gray
    
    $tags = New-Object System.Collections.Generic.HashSet[string]
    
    $configFiles = Get-ChildItem -Path $RepositoryPath -Recurse -Include "appsettings*.json", "*.config", "*.cs" -ErrorAction SilentlyContinue | 
        Where-Object { $_.FullName -notlike "*\bin\*" -and $_.FullName -notlike "*\obj\*" } |
        Select-Object -First 30
    
    foreach ($file in $configFiles) {
        $content = Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue
        if (-not $content) { continue }
        
        if ($content -match 'SqlServer|Server=|Data Source=.*\.database\.windows\.net') { [void]$tags.Add("SQL Server") }
        if ($content -match 'PostgreSQL|Npgsql') { [void]$tags.Add("PostgreSQL") }
        if ($content -match 'MySQL|MariaDB') { [void]$tags.Add("MySQL") }
        if ($content -match 'MongoDB') { [void]$tags.Add("MongoDB") }
        if ($content -match 'Redis|StackExchange\.Redis') { [void]$tags.Add("Redis") }
        if ($content -match 'Cosmos|CosmosDB') { [void]$tags.Add("Cosmos DB") }
        if ($content -match 'Oracle') { [void]$tags.Add("Oracle") }
        if ($content -match 'SQLite') { [void]$tags.Add("SQLite") }
        if ($content -match 'Elasticsearch') { [void]$tags.Add("Elasticsearch") }
    }
    
    return @($tags | Sort-Object)
}

function Detect-BusinessDomainTags {
    Write-Host "  💼 Detecting business domains..." -ForegroundColor Gray
    
    $tags = New-Object System.Collections.Generic.HashSet[string]
    
    # Scan file and folder names for domain indicators
    $allItems = Get-ChildItem -Path $RepositoryPath -Recurse -ErrorAction SilentlyContinue | 
        Where-Object { $_.FullName -notlike "*\node_modules\*" -and $_.FullName -notlike "*\bin\*" -and $_.FullName -notlike "*\obj\*" } |
        Select-Object -First 200
    
    $names = $allItems | ForEach-Object { $_.Name }
    $allText = $names -join " "
    
    # E-commerce
    if ($allText -match 'Cart|Order|Product|Payment|Checkout|Invoice|Shipping') {
        [void]$tags.Add("E-commerce")
    }
    
    # HR/Payroll (Paycor specific)
    if ($allText -match 'Payroll|Employee|Compensation|Benefit|TimeCard|Attendance|Hiring|Onboarding') {
        [void]$tags.Add("HR Management")
        [void]$tags.Add("Payroll")
    }
    
    # Financial
    if ($allText -match 'Account|Transaction|Ledger|Banking|Finance|Budget') {
        [void]$tags.Add("Financial Services")
    }
    
    # Healthcare
    if ($allText -match 'Patient|Medical|Health|Clinic|Appointment|Diagnosis') {
        [void]$tags.Add("Healthcare")
    }
    
    # Education
    if ($allText -match 'Student|Course|Enrollment|Grade|Teacher|Lesson') {
        [void]$tags.Add("Education")
    }
    
    # CRM
    if ($allText -match 'Customer|Lead|Contact|Opportunity|Campaign|Sales') {
        [void]$tags.Add("CRM")
    }
    
    # Authentication/Identity
    if ($allText -match 'Auth|Identity|Login|User|Permission|Role|Claims') {
        [void]$tags.Add("Authentication")
        [void]$tags.Add("Identity Management")
    }
    
    # Reporting/Analytics
    if ($allText -match 'Report|Dashboard|Analytics|Metrics|Chart|Export') {
        [void]$tags.Add("Reporting")
        [void]$tags.Add("Analytics")
    }
    
    # Notifications
    if ($allText -match 'Notification|Email|SMS|Alert|Message') {
        [void]$tags.Add("Notifications")
    }
    
    # Document Management
    if ($allText -match 'Document|File|Upload|Download|Storage') {
        [void]$tags.Add("Document Management")
    }
    
    # Workflow/Automation
    if ($allText -match 'Workflow|Automation|Process|Orchestrat') {
        [void]$tags.Add("Workflow Automation")
    }
    
    # Integration
    if ($allText -match 'Integration|Webhook|API|Sync|Import|Export') {
        [void]$tags.Add("Integration")
    }
    
    return @($tags | Sort-Object)
}

function Detect-ApplicationTypeTags {
    Write-Host "  📱 Detecting application types..." -ForegroundColor Gray
    
    $tags = New-Object System.Collections.Generic.HashSet[string]
    
    # Check for API
    $hasControllers = (Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*Controller.cs" -ErrorAction SilentlyContinue | 
        Where-Object { $_.FullName -notlike "*\bin\*" }).Count -gt 0
    
    if ($hasControllers) {
        [void]$tags.Add("REST API")
        [void]$tags.Add("Web API")
    }
    
    # Check for Azure Functions
    $hasFunctions = (Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*.cs" -ErrorAction SilentlyContinue | 
        Where-Object { $_.FullName -notlike "*\bin\*" } |
        Select-Object -First 20 |
        ForEach-Object { Get-Content $_.FullName -Raw -ErrorAction SilentlyContinue } |
        Where-Object { $_ -match '\[FunctionName\(' }).Count -gt 0
    
    if ($hasFunctions) {
        [void]$tags.Add("Serverless")
        [void]$tags.Add("Azure Functions")
    }
    
    # Check for UI
    $hasUI = (Test-Path (Join-Path $RepositoryPath "wwwroot")) -or
             ((Get-ChildItem -Path $RepositoryPath -Recurse -Include "*.razor", "*.cshtml", "*.tsx", "*.jsx" -ErrorAction SilentlyContinue).Count -gt 0)
    
    if ($hasUI) {
        [void]$tags.Add("Web Application")
        
        # Check specific UI framework
        if ((Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*.razor" -ErrorAction SilentlyContinue).Count -gt 0) {
            [void]$tags.Add("Blazor")
        }
        if ((Get-ChildItem -Path $RepositoryPath -Recurse -Include "*.tsx", "*.jsx" -ErrorAction SilentlyContinue).Count -gt 0) {
            [void]$tags.Add("SPA")
        }
    }
    
    # Check for background services
    $hasBackgroundServices = (Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*.cs" -ErrorAction SilentlyContinue | 
        Where-Object { $_.FullName -notlike "*\bin\*" } |
        Select-Object -First 20 |
        ForEach-Object { Get-Content $_.FullName -Raw -ErrorAction SilentlyContinue } |
        Where-Object { $_ -match 'BackgroundService|IHostedService' }).Count -gt 0
    
    if ($hasBackgroundServices) {
        [void]$tags.Add("Background Workers")
    }
    
    # Check for message processing
    $hasMessageHandlers = (Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*.cs" -ErrorAction SilentlyContinue | 
        Where-Object { $_.FullName -notlike "*\bin\*" } |
        Select-Object -First 20 |
        ForEach-Object { Get-Content $_.FullName -Raw -ErrorAction SilentlyContinue } |
        Where-Object { $_ -match 'IConsumer<|IHandleMessages<' }).Count -gt 0
    
    if ($hasMessageHandlers) {
        [void]$tags.Add("Message Processing")
    }
    
    return @($tags | Sort-Object)
}

function Detect-QualityTags {
    Write-Host "  ✅ Detecting quality practices..." -ForegroundColor Gray
    
    $tags = New-Object System.Collections.Generic.HashSet[string]
    
    # Check for testing
    $testProjects = (Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*test*.csproj" -ErrorAction SilentlyContinue | 
        Where-Object { $_.FullName -notlike "*\bin\*" }).Count
    
    if ($testProjects -gt 0) {
        [void]$tags.Add("Unit Testing")
    }
    
    # Check for CI/CD
    $hasCICD = (Test-Path (Join-Path $RepositoryPath ".github\workflows")) -or
               (Test-Path (Join-Path $RepositoryPath "azure-pipelines.yml")) -or
               (Test-Path (Join-Path $RepositoryPath ".gitlab-ci.yml"))
    
    if ($hasCICD) {
        [void]$tags.Add("CI/CD")
    }
    
    # Check for infrastructure as code
    $hasTerraform = (Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*.tf" -ErrorAction SilentlyContinue).Count -gt 0
    if ($hasTerraform) {
        [void]$tags.Add("Terraform")
        [void]$tags.Add("Infrastructure as Code")
    }
    
    $hasBicep = (Get-ChildItem -Path $RepositoryPath -Recurse -Filter "*.bicep" -ErrorAction SilentlyContinue).Count -gt 0
    if ($hasBicep) {
        [void]$tags.Add("Bicep")
        [void]$tags.Add("Infrastructure as Code")
    }
    
    return @($tags | Sort-Object)
}

function Generate-SEOKeywords {
    param($AllTags)
    
    # Generate SEO-friendly keywords from tags
    $keywords = @()
    
    foreach ($tag in $AllTags) {
        $keywords += $tag
        
        # Add variations
        if ($tag -eq "ASP.NET Core") { $keywords += @("aspnet", "dotnet api", "c# web api") }
        if ($tag -eq "Azure Functions") { $keywords += @("serverless", "faas", "azure serverless") }
        if ($tag -eq "CQRS") { $keywords += @("command query", "event sourcing") }
        if ($tag -eq "Microservices") { $keywords += @("distributed systems", "service oriented") }
    }
    
    return @($keywords | Select-Object -Unique | Sort-Object)
}

# Main Tag Generation
$allTags = @{
    Frameworks = Detect-FrameworkTags
    Architecture = Detect-ArchitectureTags
    Cloud = Detect-CloudTags
    Database = Detect-DatabaseTags
    BusinessDomain = Detect-BusinessDomainTags
    ApplicationType = Detect-ApplicationTypeTags
    Quality = Detect-QualityTags
}

# Flatten all tags
$flatTags = @()
foreach ($category in $allTags.Keys) {
    $flatTags += $allTags[$category]
}
$flatTags = @($flatTags | Select-Object -Unique | Sort-Object)

# Generate keywords
$keywords = Generate-SEOKeywords -AllTags $flatTags

$result = @{
    Repository = Split-Path $RepositoryPath -Leaf
    GeneratedAt = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    TagsByCategory = $allTags
    AllTags = $flatTags
    Keywords = $keywords
    TotalTags = $flatTags.Count
}

Write-Host "✅ Tag generation complete!" -ForegroundColor Green
Write-Host "  Total Tags: $($flatTags.Count)" -ForegroundColor Gray
Write-Host "  Keywords: $($keywords.Count)" -ForegroundColor Gray

return $result
