// Generated by AI on 06/15/2026
// Modified by AI on 06/15/2026. Edit #1 - wire EditVersionModal and updateVersion.

import { useState } from 'react';
import { Container, Toast, ToastContainer } from 'react-bootstrap';
import { useVersions } from './hooks/useVersions';
import { VersionList } from './components/VersionList';
import { AddVersionForm } from './components/AddVersionForm';
import { EditVersionModal } from './components/EditVersionModal';
import { SettingsPanel } from './components/SettingsPanel';
import { SetupGuide } from './components/SetupGuide';
import { JavaVersion } from './types';

interface ToastState {
  message: string;
  variant: 'success' | 'danger';
}

function App() {
  const { versions, settings, activeId, error, addVersion, updateVersion, deleteVersion, switchVersion, saveSettings } = useVersions();
  const [switchingId, setSwitchingId] = useState<string | null>(null);
  const [toast, setToast] = useState<ToastState | null>(null);
  const [editingVersion, setEditingVersion] = useState<JavaVersion | null>(null);

  const showToast = (message: string, variant: 'success' | 'danger') => {
    setToast({ message, variant });
  };

  const handleSwitch = async (id: string) => {
    setSwitchingId(id);
    try {
      const message = await switchVersion(id);
      showToast(message, 'success');
    } catch (err) {
      const msg = (err as Error).message;
      if (msg.includes('connect') || msg.includes('fetch')) {
        showToast('Could not connect to the server. Is it still running?', 'danger');
      } else {
        showToast(msg, 'danger');
      }
    } finally {
      setSwitchingId(null);
    }
  };

  const handleDelete = async (id: string) => {
    try {
      await deleteVersion(id);
    } catch (err) {
      showToast((err as Error).message, 'danger');
    }
  };

  const handleAdd = async (name: string, path: string) => {
    await addVersion(name, path);
  };

  const handleEdit = async (id: string, name: string, path: string) => {
    await updateVersion(id, name, path);
  };

  const handleSaveSettings = async (envVarName: string) => {
    await saveSettings(envVarName);
  };

  return (
    <>
      <ToastContainer position="top-end" className="p-3" style={{ zIndex: 9999 }}>
        {toast && (
          <Toast
            bg={toast.variant}
            onClose={() => setToast(null)}
            show
            delay={6000}
            autohide
          >
            <Toast.Header>
              <strong className="me-auto">
                {toast.variant === 'success' ? '✅ Switched' : '❌ Error'}
              </strong>
            </Toast.Header>
            <Toast.Body className={toast.variant === 'success' ? '' : 'text-white'}>
              {toast.message}
            </Toast.Body>
          </Toast>
        )}
      </ToastContainer>

      <Container className="py-4">
        <h1 className="mb-1">Java Context Switcher</h1>
        <p className="text-muted mb-4">
          Click a version to set <code>{settings.envVarName}</code> on your machine.
        </p>

        {error && <div className="alert alert-warning">Backend error: {error}</div>}

        <VersionList
          versions={versions}
          activeId={activeId}
          switchingId={switchingId}
          onSwitch={(id) => { void handleSwitch(id); }}
          onDelete={(id) => { void handleDelete(id); }}
          onEdit={(v) => setEditingVersion(v)}
        />

        <EditVersionModal
          version={editingVersion}
          onSave={(id, name, path) => handleEdit(id, name, path)}
          onClose={() => setEditingVersion(null)}
        />

        <div className="mt-4">
          <AddVersionForm onAdd={handleAdd} />
        </div>

        <hr className="my-4" />

        <SetupGuide />

        <div className="mt-3">
          <SettingsPanel settings={settings} onSave={handleSaveSettings} />
        </div>
      </Container>
    </>
  );
}

export default App;
