// Generated by AI on 06/15/2026
// No-op code signing hook for electron-builder.
// Prevents winCodeSign tool download (which requires symlink privilege on Windows).
exports.default = async function () {
  // Intentionally skip signing
};
